#+TITLE: Emacs configuration
Inspired by [[https://github.com/hrs/dotfiles/tree/master/emacs.d][hrs]] and [[https://github.com/pierre-lecocq/emacs.d/tree/literal][pierre-lecocq]] org configs

* General
** Lexical binding
   Enable lexical binding in this config
   #+begin_src emacs-lisp
   ;; -*- lexical-binding: t -*-
   #+end_src
** Customizations
   Set emacs to save the customizations in a separate file to avoid
   having them in the git repo.
   #+begin_src emacs-lisp
     (setq custom-file (concat user-emacs-directory ".custom.el"))
     (when (file-exists-p custom-file)
         (load custom-file))
   #+end_src
** Package management

   Setup repositories for package and auto download use-package if it's missing.
   #+begin_src emacs-lisp
     (require 'package)

     (setq package-archives
           '(("melpa-stable" . "https://stable.melpa.org/packages/")
             ("melpa"        . "https://melpa.org/packages/")
             ("gnu"          . "https://elpa.gnu.org/packages/")
             ("org"          . "https://orgmode.org/elpa/")))

     (package-initialize)

     (when (not package-archive-contents)
       (package-refresh-contents))

     (setq package-enable-at-startup nil)

     (unless (getenv "GUIX_PROFILE")
       ;; Pin melpa-stable for packages not under use-package control, i.e
       ;; dependencies and use-package itself.
       (setq package-pinned-packages
             '((use-package . "melpa")
               ;; Deps
               (async       . "melpa")
               (bind-key    . "melpa-stable")
               (dash        . "melpa")
               (diminish    . "melpa-stable")
               (epl         . "melpa-stable")
               (git-commit  . "melpa")
               (magit-popup . "melpa")
               (pkg-info    . "melpa-stable")
               (popup       . "melpa-stable")
               (s           . "melpa-stable")
               (with-editor . "melpa")))

       (unless (package-installed-p 'use-package)
         (package-install 'use-package))
       (unless (package-installed-p 'diminish)
         (package-install 'diminish)))
   #+end_src

   Let use-package handle all the packages I use
   #+begin_src emacs-lisp
     (eval-when-compile
       (require 'use-package))
     (require 'diminish)                ;; if you use :diminish
     (require 'bind-key)                ;; if you use any :bind variant
   #+end_src

   Install missing packages.
   #+begin_src emacs-lisp
     (setq use-package-always-ensure (not (getenv "GUIX_PROFILE")))
   #+end_src
** Custom plugins
*** Dotemacs
    Export a variable if I'm at work or not.
    #+begin_src emacs-lisp
      (use-package dotemacs
        :ensure nil
        :load-path "plugins")
    #+end_src
** UI
*** Maximize work area
   Disable the menu, tool and scroll bar since they just take up
   space.
   #+begin_src emacs-lisp
     (menu-bar-mode 0)
     (tool-bar-mode 0)
     (when (window-system) (scroll-bar-mode 0))
   #+end_src
*** Font
    Set font and font size
    #+begin_src emacs-lisp
      (set-frame-font "Hack:pixelsize=12" nil t)
    #+end_src
*** Column number
   Show column number in the info bar
   #+begin_src emacs-lisp
     (column-number-mode 1)
   #+end_src
** Behaviour
   Changing the default emacs behavior to better suite me.
   #+begin_src emacs-lisp
     (setq-default
      electric-indent-mode nil        ;; Disable electric-indent-mode, C-j is used for that.
      load-prefer-newer t             ;; Avoid loading outdated byte code files.
      auto-hscroll-mode 'current-line ;; Activate single-line horizontal scrolling mode (emacs-26 and up).
      inhibit-splash-screen t         ;; Dismiss the startup screen.
      initial-scratch-message nil     ;; Empty scratch buffer.
      indent-tabs-mode nil            ;; Don't use tab for indenting.
      sentence-end-double-space nil   ;; Use sane defaults for sentences.
      show-trailing-whitespace t
      display-time-24hr-format t
      scroll-step           1         ;; smooth scrolling
      scroll-conservatively 10000
      enable-recursive-minibuffers t) ;; Allow to use the minibuffer while using the minibuffer
     (show-paren-mode 1)                ;; Highlight matching brackets.
     (minibuffer-depth-indicate-mode 1) ;; Keep track of which minibuffer

   #+end_src

   Don't popup a new frame but reuse one that is already open. If no
   other frame is open, open in the same frame.
   #+begin_src emacs-lisp
     (setq display-buffer--other-frame-action
           '((display-buffer-reuse-window display-buffer-use-some-frame)
             (reusable-frames . visible)
             (inhibit-same-window . t)
             (inhibit-switch-frame . t)))
   #+end_src
**** Trailing Whitespaces

     Show trailing whitespaces by default for writeable buffers. Turn it
     off for read only as it is distracting and you cannot remove them
     anyway.

     #+begin_src emacs-lisp
       (add-hook 'find-file-hook
                 (lambda () (setq show-trailing-whitespace (not buffer-read-only))))
       (add-hook 'read-only-mode-hook
                 (lambda () (setq show-trailing-whitespace (not buffer-read-only))))
     #+end_src

     Show trailing whitespaces for all comint modes: shell, gdb,
     geiser REPL etc.

     #+begin_src emacs-lisp
       (use-package comint
         :ensure nil ; Built in
         :config
         (add-hook 'comint-mode-hook 'dotemacs-hide-trailing-whitespace))
     #+end_src

**** Read only

     Change the cursor when in a read only buffer.
     #+begin_src emacs-lisp
       (add-hook 'read-only-mode-hook
                 (lambda () (setq-local cursor-type (if buffer-read-only 'hbar 'box))))
     #+end_src

** Calender
   #+begin_src emacs-lisp
     (setq-default
      calendar-week-start-day 1       ;; Week starts on Monday.
      calendar-day-name-array
      ["söndag" "måndag" "tisdag" "onsdag" "torsdag" "fredag" "lördag"]
      calendar-month-name-array
      ["januari" "februari" "mars" "april" "maj" "juni"
       "juli" "augusti" "september" "oktober" "november" "december"]
      calendar-time-display-form '(24-hours ":" minutes (if time-zone " (") time-zone (if time-zone ")"))
      calendar-date-style 'european)
   #+end_src

   Hide trailing whitespaces for calendar mode, as there are a bunch
   of those showing up in the calendar.
   #+begin_src emacs-lisp
     (add-hook 'calendar-mode-hook 'dotemacs-hide-trailing-whitespace)
   #+end_src
** Backup/autosave
   One annoying thing with emacs is it that it leaves backup files all
   over the place.  Fixing that by dumping all backup/autosave files
   in to one directory.
   #+begin_src emacs-lisp
     (let ((backup-dir (file-name-as-directory (concat user-emacs-directory "backup")))
           (autosave-dir
            (file-name-as-directory (concat user-emacs-directory "autosave"))))
       (setq backup-directory-alist (list (cons ".*" backup-dir))
             auto-save-list-file-prefix autosave-dir
             auto-save-file-name-transforms `((".*" ,autosave-dir t))))
   #+end_src
** Theme
   Point emacs to where it can find the sunburst theme.
   #+begin_src emacs-lisp
     (add-to-list 'custom-theme-load-path
                  (dotemacs-build-path user-emacs-directory "themes" "plattfot-theme"))
     (load-theme `plattfot t)
   #+end_src
** Path
   #+begin_src emacs-lisp
     (add-to-list 'exec-path (expand-file-name "~/bin"))
   #+end_src
* Packages
** Code
*** Autocomplete
   Packages that helps speed up coding, i.e. auto complete, boiler plates etc
**** Company

     Configure company to work similar to auto complete. Disabled most
     backends for c++ when at work as they were either slow, failed to
     find a completion half the time or flat out crashed clang when
     trying to complete stuff. The company-dabbrev-code works similar
     to what I had before with ac.

     #+begin_src emacs-lisp
       (use-package company
         :bind ( ("C-<tab>" . company-complete-common)
                 :map company-active-map
                 ("C-n" . company-select-next)
                 ("C-p" . company-select-previous))
         :init
         ;; List what modes to use company in.
         (add-hook 'after-init-hook 'global-company-mode)
         :config
         (setq company-global-modes '(not shell-mode gud-mode eshell-mode)
               company-idle-delay 0.1
               company-minimum-prefix-length 3
               company-clang-insert-arguments nil
               company-dabbrev-downcase nil
               company-dabbrev-ignore-case nil
               company-dabbrev-other-buffers t
               company-dabbrev-code-other-buffers t
               company-lighter-base "c")

         (add-hook 'org-mode-hook
                   (lambda ()
                     ;; Remove dabbrev from org-mode as it's driving me crazy!
                     (set (make-local-variable 'company-backends)
                          (setq-local company-backends
                                      (delete 'company-dabbrev company-backends)))
                     ;; Fixing capf to work with org-mode
                     ;; https://emacs.stackexchange.com/a/21173
                     (add-hook 'completion-at-point-functions
                               'pcomplete-completions-at-point nil t)))
         (add-hook 'emacs-lisp-mode-hook
                   (lambda ()
                     (set (make-local-variable 'company-backends)
                          '((company-capf
                             company-dabbrev-code
                             :separate)))))
         (add-hook 'c-mode-common-hook
                     (lambda ()
                       (when (and (buffer-file-name) (file-remote-p (buffer-file-name)))
                         (set (make-local-variable 'company-backends)
                            '(company-dabbrev-code)))))
         ;; Only reliable backend at work
         (when dotemacs-is-work
           (add-hook 'c-mode-common-hook
                     (lambda ()
                       (set (make-local-variable 'company-backends)
                            '(company-dabbrev-code)))))
         :pin melpa-stable)
     #+end_src

     Tell emacs it's safe to change these company variables in a
     .dir-locals.el file.
     #+begin_src emacs-lisp
       (put 'company-clang-executable 'safe-local-variable #'stringp)
       (put 'company-clang-arguments 'safe-local-variable #'listp)
     #+end_src

**** Yasnippet
     Enable yasnippet
     #+begin_src emacs-lisp
       (use-package yasnippet
       	 :config
       	 (yas-global-mode 1)
       	 (setq yas-indent-line nil)
       	 :pin melpa-stable)
     #+end_src
**** eglot
     Client for Language Server Protocol (lsp) servers.

     Tried both ~lsp-mode~ and ~eglot~. And for my use case ~eglot~ is
     better. ~lsp-mode~ involved a lot more tweaking to get it working
     (e.g. make sure ~company-capf~ is first in ~company-backends~).
     Once I got it working the completion menu in company was a lot
     nosier than what I get from ~eglot~. Only issue I have with
     ~eglot~ is the face in the mode-line. My mode-line is monochrome
     and is grayed out when the frame is not in focus. Which ~eglot~
     does not respect and by default it stands out like a sore thumb
     (I have the same issue with ~flymake~ and ~compilation~). I have
     tweaked my theme so it is not so bad. Still annoying though.

     *NOTE:* clangd also accepts arguments from the environment
      variable ~CLANGD_FLAGS~. I'm using that combined with ~direnv~
      to specify where the ~compile_commands.json~ is located. As that
      can change from project to project.

      For example set that ~compile_commands.json~ is in the
      subdirectory ~build~ in the root of the project.

     #+begin_src sh :tangle no
       # .envrc
       export CLANGD_FLAGS="--compile-commands-dir=./build"
     #+end_src

     #+begin_src emacs-lisp
       (use-package eglot
         :config
         ;; Only run eglot on local buffers, too slow on bad connections.
         (add-hook 'c++-mode-hook
                   (lambda ()
                     (when (and (buffer-file-name) (not (file-remote-p (buffer-file-name))))
                       (eglot-ensure))))
         (setq gc-cons-threshold 100000000
               read-process-output-max (* 1024 1024) ;; 1mb
               company-minimum-prefix-length 1
               company-idle-delay 0.0)
         (add-to-list 'eglot-server-programs
                      '(c++-mode . ("clangd"
                                    "--background-index"
                                    "--header-insertion=iwyu"
                                    "--pch-storage=memory"
                                    "-j=6"))))
     #+end_src
**** lsp
     #+begin_src emacs-lisp
       (use-package lsp-mode
         :ensure t
         :disabled t
         :config
         (setq gc-cons-threshold 100000000
               read-process-output-max (* 1024 1024) ;; 1mb
               company-minimum-prefix-length 1
               company-idle-delay 0.0
               lsp-prefer-capf t)
         (add-hook 'prog-mode-hook #'lsp)
         (add-hook 'hack-local-variables-hook
                   (lambda () (when (derived-mode-p 'prog-mode) (lsp))))
         (setq lsp-clients-clangd-args '("--compile-commands-dir=./build"
                                         "--background-index"
                                         "-j=6"
                                         "--header-insertion=iwyu"))
         (add-hook 'prog-mode-hook
                   (lambda ()
                     (setq company-backends
                           `(company-capf ,@(--filter (not (equal 'company-capf it))
                                                      company-backends))))))
       (put 'lsp-clients-clangd-args 'safe-local-variable #'listp)

     #+end_src
*** Lint
   Packages that helps inspecting code, report errors etc.
**** Flymake

     Moved over to using ~flymake~ instead of ~flycheck~. Mainly
     because it is the only one that works with ~eglot~ so keeping it
     consitent between modes.

     #+begin_src emacs-lisp
       (use-package flymake
         :ensure nil ; built-in
         :config
         (add-hook 'prog-mode-hook 'flymake-mode))
     #+end_src

     Flymake lacks linting for shell scripts. Testing out shellcheck.
     #+begin_src emacs-lisp
       (use-package flymake-shellcheck
         :ensure t
         :commands flymake-shellcheck-load
         :init
         (add-hook 'sh-mode-hook 'flymake-shellcheck-load))
     #+end_src

** Programming languages
  Modes for highlighting different programing languages.
*** Haskell
    Settings for programming haskell in emacs
    #+begin_src emacs-lisp
      (use-package haskell-mode
        :config
        (add-hook 'haskell-mode-hook 'turn-on-haskell-doc-mode)
        (add-hook 'haskell-mode-hook 'turn-on-haskell-indent)
        (autoload 'ghc-init "ghc" nil t)
        :pin melpa-stable)
    #+end_src
*** Lisp
    Color haxvalues with their respective color.
    #+begin_src emacs-lisp
      (use-package lisp-mode
        :ensure nil ; Built in
        :config
        (defvar hexcolour-keywords
          '(("#[[:xdigit:]]\\{6\\}"
             (0 (put-text-property (match-beginning 0)
                                   (match-end 0)
                                   'face (list :background
                                               (match-string-no-properties 0)))))))
        (add-hook 'lisp-mode-hook
                  (lambda ()
                    (font-lock-add-keywords nil hexcolour-keywords))))
    #+end_src
**** Smartparens

     Having issues with turning off auto balancing, i.e
     (|) - insert () -> (()|
     #+begin_src emacs-lisp
       (use-package smartparens
         :init
         ;;(add-hook 'c-mode-hook 'turn-on-smartparens-mode)
         ;;(add-hook 'c++-mode-hook 'turn-on-smartparens-mode)
         (add-hook 'lisp-mode-hook 'turn-on-smartparens-mode)
         (add-hook 'scheme-mode-hook 'turn-on-smartparens-mode)
         (add-hook 'guile-mode-hook 'turn-on-smartparens-mode)
         (add-hook 'emacs-lisp-mode-hook 'turn-on-smartparens-mode)
         ;; (add-hook 'python-mode 'turn-on-smartparens-mode)
         (add-hook 'lisp-interaction-mode-hook 'turn-on-smartparens-mode)
         :bind (:map smartparens-mode-map
                     ("C-)" . sp-forward-slurp-sexp)
                     ("C-(" . sp-backward-slurp-sexp)
                     ("C-}" . sp-forward-barf-sexp)
                     ("C-{" . sp-backward-barf-sexp)
                     ("C-M-a" . sp-beginning-of-sexp)
                     ("C-M-e" . sp-end-of-sexp)
                     ("C-M-t" . sp-transpose-hybrid-sexp)
                     ("C-M-s" . sp-splice-sexp-killing-around)
                     ("M-s" . sp-split-sexp)
                     ("M-[" . sp-backward-unwrap-sexp)
                     ("M-]" . sp-unwrap-sexp)
                     ("M-}" . sp-splice-sexp-killing-backward)
                     ("M-{" . sp-splice-sexp-killing-forward))
         :config
         ;; Turn off balancing of single and back quote in lisp.
         (sp-with-modes sp--lisp-modes
           (sp-local-pair "'" nil :actions nil)
           (sp-local-pair "`" nil :actions nil))
         :pin melpa-stable)
     #+end_src
*** C family
    Specific for C, C++ and other in the c family
    - Set indentation to be two spaces.
    - Set the default mode for .h files to be c++-mode
    - Make it easier to work with camelCase words by enabling subword-mode.
    - Add that it will also search src and include directories when
      switching between header and source files.

    Custom style based on gnu for work. See [[https://www.gnu.org/software/emacs/manual/html_node/ccmode/Adding-Styles.html#Adding-Styles][adding-styles]] for more
    info how this work. [[https://www.gnu.org/software/emacs/manual/html_node/ccmode/Guessing-the-Style.html][Guessing]] the style also work, but it was
    easier for me to just place the pointer at a location and press
    C-c C-o (c-set-offset) and add that to the c-offsets-alist.

    When in a c family buffer use shift tab to switch between header
    and source.

    #+begin_src emacs-lisp
      (c-add-style "dd"
                   '("gnu"
                     (c-basic-offset . 2)
                     (c-offsets-alist
                      (substatement-open . 0)
                      (arglist-close . 0)
                      (arglist-intro . +)
                      (statement-case-open . 0)
                      (brace-list-intro . +))))
    #+end_src
    #+begin_src emacs-lisp
      (use-package cc-mode
        :mode ("\\.h\\'" . c++-mode)
        :ensure nil ;; built in
        :config
        ;; Call everytime an c-mode-common file is opened
        (add-hook 'c-mode-common-hook
                  (lambda ()
                    ;; Set keybinding for all cc-modes
                    (local-set-key  (kbd "<backtab>") 'ff-find-other-file)
                    (local-set-key  (kbd "<C-iso-lefttab>") 'ff-extension-other-impl)

                    (setq indent-tabs-mode nil)
                    (c-set-style "dd")
                    ;; enable camelCase
                    (subword-mode 1)))
        (setq ff-search-directories '("." "../src" "../include"))
        :pin melpa-stable)
    #+end_src
*** Python
    Package name is python but the mode is python-mode
    Set indentation to 2 white spaces.

    Set the default for pb2 files (=PROJECT=) to use python.
    #+begin_src emacs-lisp
      (use-package python
        :mode (("\\.py\\'" . python-mode)
               ("PROJECT$" . python-mode))
        :interpreter ("python" . python-mode)
        :config
        (add-hook 'python-mode-hook
                  (lambda ()
                    (setq indent-tabs-mode nil
                          python-indent-offset 4)))
        :pin melpa-stable)
    #+end_src

    #+begin_src emacs-lisp
      (use-package jinja2-mode
        :pin melpa-stable)
    #+end_src
*** Rust

    Packages for setting up a rust environment
    #+begin_src emacs-lisp
      (use-package rust-mode
        :pin melpa-stable)
    #+end_src

    Mode for editing Cargo files.
    #+begin_src emacs-lisp
      (use-package toml-mode
        :pin melpa)
    #+end_src

*** Golang
    Setting up go to use 2 spaces as indentation and enable
    autocomplete for go.
    #+begin_src emacs-lisp
      (use-package go-mode
        :config
        (add-hook 'go-mode-hook
                  (lambda ()
                    (setq tab-width 2
                          standard-indent 2
                          indent-tabs-mode nil)))
        :pin melpa-stable)
    #+end_src
*** Shaders
**** GLSL
     Set files associated with glsl to use glsl mode
     #+begin_src emacs-lisp
       (use-package glsl-mode
         :mode (("\\.vert\\'" . glsl-mode)
                ("\\.frag\\'" . glsl-mode)
                ("\\.geom\\'" . glsl-mode)
                ("\\.prog\\'" . glsl-mode)
                ("\\.glsl\\'" . glsl-mode))
         :pin melpa)
     #+end_src

*** Build
**** Makefile
     Set following files to use makefile-gmake-mode as the default.
     - Files that starts with =Makefile=.
     - Has extension =.mk=.

     Show trailing whitespace as those can mess up make pretty bad.
     #+begin_src emacs-lisp
       (use-package make-mode
         :mode (("Makefile.*" . makefile-gmake-mode)
                ("\\.mk$" . makefile-gmake-mode))
         :config
         (add-hook 'makefile-mode-hook
                   (lambda ()
                     ;; Always show trailing whitespace for Makefiles
                     ;; Don't break words
                     (setq show-trailing-whitespace t
                           word-wrap t))))
     #+end_src
**** CMake
     #+begin_src emacs-lisp
       (use-package cmake-mode
       	 :pin melpa-stable)
     #+end_src
*** REPL
**** Geiser
     #+begin_src emacs-lisp
       (use-package geiser
         :hook (scheme-mode-hook)
         :config
         (setq geiser-default-implementation 'guile
               geiser-repl-use-other-window nil)
         :pin melpa-stable)
     #+end_src
     Auto complete backend for geiser
     #+begin_src emacs-lips
	 (use-package ac-geiser
	   :pin melpa-stable)
     #+end_src
**** Sh
     Indent using 2 spaces for shell scripts.
     #+begin_src emacs-lisp
       (use-package sh-script
         :config
         (add-hook 'sh-mode-hook
               (lambda ()
                 (setq indent-tabs-mode nil
                       c-basic-offset 2))))
     #+end_src
*** Yaml
    #+begin_src emacs-lisp
      (use-package yaml-mode
       	:pin melpa-stable)
    #+end_src
*** json
    #+begin_src emacs-lisp
      (use-package json-mode
        :pin melpa-stable)
    #+end_src
*** Markdown
    #+begin_src emacs-lisp
      (use-package markdown-mode
       	:pin melpa-stable)
    #+end_src
*** Meson
   #+begin_src emacs-lisp
     (use-package meson-mode
       :pin melpa)
   #+end_src
*** Julia
    #+begin_src emacs-lisp
      (use-package julia-mode
        :pin melpa)
    #+end_src
*** Systemd
    #+begin_src emacs-lisp
      (use-package systemd
        :pin melpa-stable)
    #+end_src
*** GDB script
    #+begin_src emacs-lisp
      (use-package gud
        :mode (("\\.gdbinit$" . gdb-script-mode))
        :ensure nil)
    #+end_src
*** lua
    #+begin_src emacs-lisp
      (use-package lua-mode
        :ensure t
        :pin melpa)
    #+end_src
** Programs
  Packages that communicates with external processes.
*** Ledger
   Settings for ledger.
   Set the default mode for .dat files to ledger.

   Clean the buffer with C-c C.

   #+begin_src emacs-lisp
     (use-package ledger-mode
       :ensure t
       :bind (:map ledger-mode-map
                   ("C-c C" . ledger-mode-clean-buffer))
       :mode "\\.dat\\'"
       :config
       (add-hook 'ledger-mode-hook #'ledger-flymake-enable)
       (setq ledger-clear-whole-transactions 1
             ledger-schedule-file "~/projects/bokforing/schedule.ledger"
             ledger-schedule-look-backward 5
             ledger-schedule-look-forward 30
             ledger-amount-regex
             (concat "\\(  \\|\t\\| \t\\)[ \t]*-?"
                     "(?"
                     "\\(?:"
                     "\\([A-Z$€£₹_(]+ *\\)?"
                     ;; We either match just a number after the commodity with no
                     ;; decimal or thousand separators or a number with thousand
                     ;; separators.  If we have a decimal part starting with `,'
                     ;; or `.', because the match is non-greedy, it must leave at
                     ;; least one of those symbols for the following capture
                     ;; group, which then finishes the decimal part.
                     "\\(-?\\(?:[0-9]+\\|[0-9,.]+?\\)\\)"
                     "\\([,.][0-9)]+\\)?"
                     "\\( *[[:word:]€£₹_\"]+\\)?"
                     "\\(?:[ \t]*[+*/-][ \t]*\\)?"
                     "\\)+"
                     ")?"
                     "\\([ \t]*[@={]@?[^\n;]+?\\)?"
                     "\\([ \t]+;.+?\\|[ \t]*\\)?$"))
       (add-hook 'ledger-mode-hook
                 (lambda ()
                   (setq-local company-backends '(company-capf))
                   (setq-local tab-always-indent 'complete)
                   (setq-local completion-ignore-case t)
                   (setq-local ledger-complete-in-steps t)))
       :pin melpa)
   #+end_src
*** direnv
    #+begin_src emacs-lisp
      (use-package direnv
       :config
       (direnv-mode))
    #+end_src
*** Arduino
    Function for setting up a arduino template sketch
    #+begin_src emacs-lisp
      (defun init-arduino ()
      "Template arduino sketch"
      (interactive)
      (insert "void setup() {
       	// put your setup code here, to run once:

      }

      void loop() {
       	// put your main code here, to run repeatedly:

      }")
      )
    #+end_src
*** Magit
    A Git porcelain inside Emacs
    Key =C-x g= to run magit on current buffer.

    #+begin_src emacs-lisp
      (use-package transient
        :pin melpa)
    #+end_src

    #+begin_src emacs-lisp
      (use-package magit
        :after (transient)
        :bind ("C-x g" . magit-status)
        :pin melpa)
    #+end_src
*** Magithub (disabled)

    Has a bug, see [[https://github.com/magit/ghub/issues/81][#81]]. Disabling it until a work around is found. As I
    haven't started using this just yet.
    #+begin_src emacs-lisp
      (use-package magithub
        :after magit
        :disabled t
        :ensure t
        :config (magithub-feature-autoinject t)
        :pin melpa-stable)
    #+end_src
*** The Silver Searcher
    #+begin_src emacs-lisp
      (use-package ag
	:pin melpa-stable)
    #+end_src
*** notmuch

    Using notmuch to index my emails.
    #+begin_src emacs-lisp
      (use-package notmuch
        :bind ("C-c m" . notmuch)
        :config
        (define-key notmuch-search-mode-map "l"
          (lambda (&optional beg end)
            "mark thread as read"
            (interactive (notmuch-search-interactive-region))
            (notmuch-search-tag (list "-unread") beg end)
            (notmuch-search-next-thread)))
        (add-hook 'notmuch-show-hook 'dotemacs-hide-trailing-whitespace)
        (setq-default
         sendmail-program "msmtp"
         send-mail-function 'sendmail-send-it
         message-kill-buffer-on-exit t
         message-send-mail-function 'message-send-mail-with-sendmail
         message-signature "s/Fred[re]+i[ck]+/Fredrik/g"
         mm-text-html-renderer 'gnus-w3m
         notmuch-show-indent-messages-width 0
         notmuch-search-oldest-first nil
         notmuch-fcc-dirs `((,user-mail-address . "gmail/[Gmail]/Skickat"))
         notmuch-show-logo nil
         notmuch-draft-folder "gmail/[Gmail]/Utkast"
         notmuch-saved-searches '((:name "inkorgen" :query "tag:inbox" :sort-order newest-first :key "i")
                                  (:name "inkorgen (oläst)" :query "tag:unread and tag:inbox" :sort-order newest-first :key "o")
                                  (:name "oläst" :query "tag:unread" :sort-order newest-first :key "O")
                                  (:name "reklam" :query "tag:reklam and tag:unread" :key "r")
                                  (:name "stjärnmärkt" :query "tag:flagged" :key "f")
                                  (:name "skickat" :query "tag:sent" :sort-order newest-first :key "s")
                                  (:name "utkast" :query "tag:draft" :key "u")
                                  (:name "order" :query "tag:order" :key "b")
                                  (:name "allt" :query "*" :key "a")))
        :ensure nil)
    #+end_src

*** pdftools

    *NOTE:* To use this, install it externally via the distribution's
    package manager. As installing this from melpa tends to break a
    lot due it needs to be compiled.
    #+begin_src emacs-lisp
      (use-package pdf-tools
        :if (not dotemacs-is-work)
        :mode ("\\.pdf\\'" . pdf-view-mode)
        :ensure nil)
    #+end_src
*** man
    #+begin_src emacs-lisp
      (use-package man
        :config
        (when dotemacs-is-work
          (setf manual-program "pk man")))
    #+end_src
*** telegram
    #+begin_src emacs-lisp
      (use-package telega
        :if (not dotemacs-is-work)
        :config
        (add-hook 'telega-root-mode-hook 'dotemacs-hide-trailing-whitespace)
        (add-hook 'telega-chat-mode-hook 'dotemacs-hide-trailing-whitespace)
        :pin melpa-stable)
    #+end_src
*** vterm

    Workaround for killing text in vterm to the kill ring.
    #+begin_src emacs-lisp
      (defun vterm-send-C-k ()
        "Send `C-k' to libvterm."
        (interactive)
        (kill-ring-save (point) (vterm-end-of-line))
        (vterm-send-key "k" nil nil t))
    #+end_src

    Sometimes I need to run ~emacs~ inside of ~vterm~, and cannot use
    the normal ~C-x C-c~ command to exit as that will exit my real
    emacs session.
    #+BEGIN_SRC emacs-lisp
      (defun vterm-exit-emacs ()
        "Send `C-x C-c' to libvterm.

      Useful when running emacs inside of an vterm"
        (interactive)
        (vterm-send-C-x)
        (vterm-send-C-c))
    #+END_SRC

    #+begin_src emacs-lisp
      (use-package vterm
        :bind (:map vterm-mode-map
                    ("<f8>" . vterm-clear)
                    ("C-k" . vterm-send-C-k))
        :config
        (setf vterm-max-scrollback 10000)
        (add-hook 'vterm-mode-hook 'dotemacs-hide-trailing-whitespace))
    #+end_src
*** mpdel
    #+begin_src emacs-lisp
      (use-package libmpdel
        :config)
      (use-package mpdel
        :requires libmpdel)
    #+end_src
** Web
  Packages for webbased content.
*** nginx
    Major mode for editing nginx.
    #+begin_src emacs-lisp
      (use-package nginx-mode
       	:pin melpa-stable)
    #+end_src
** Emacs
  Packages that augments emacs.
*** Org

    Mostly from [[https://github.com/hrs/dotfiles/tree/master/emacs.d][hrs]] config file but converted to use-package.

    Use a little downward-pointing arrow instead of the usual ellipsis
    (=...=) when folded.

    Use syntax highlighting in source blocks while editing
    'org-src-fontify-natively'.

    The variable 'org-directory' is set in '.custom.el', as it changes
    from compute to computer at the moment.

    The org structure template el (expand using <el) is from
    [[https://github.com/freetonik/emacs-dotfiles/blob/master/init.org#org][EmacsCast]].

    #+begin_src emacs-lisp
      (use-package org
        :mode ("\\.org\\'" . org-mode)
        :bind (("C-c l" . org-store-link)
               ("C-c a" . org-agenda)
               ("C-c c" . org-capture)
               ("C-c b" . org-iswitchb))
        :config
        (setq org-ellipsis "⤵"
              org-todo-keywords
              '((sequence "TODO(t)" "WAIT(w@/!)" "|" "DONE(d!)" "CANCELLED(c@)"))
              org-default-notes-file (concat org-directory "/Anteckningar.org")
              org-agenda-span 'day
              org-agenda-window-setup 'only-window
              org-agenda-restore-windows-after-quit t
              org-src-fontify-natively t
              org-src-tab-acts-natively t
              org-enforce-todo-dependencies t
              org-confirm-babel-evaluate nil
              org-src-window-setup 'split-window-below
              org-link-search-must-match-exact-headline nil
              org-log-into-drawer "LOGBOOK")
        (when (not dotemacs-is-work)
          (add-to-list 'org-agenda-files org-directory))

        ;; Active Babel languages
        (if dotemacs-is-work
            (org-babel-do-load-languages
             'org-babel-load-languages
             '((calc . t)
               (python . t)
               (scheme . t)))
          (org-babel-do-load-languages
           'org-babel-load-languages
           '((calc . t)
             (python . t)
             (scheme . t)
             (shell . t))))
        :pin org)
    #+end_src

    Enable linking notmuch emails in org
    #+begin_src emacs-lisp
      (use-package ol-notmuch
        :after org
        :ensure nil)
    #+end_src

    #+begin_src emacs-lisp
      (use-package org-tempo
        :ensure nil
        :config
        (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp")))
    #+end_src

    #+begin_src emacs-lisp
      (use-package org-agenda
        :ensure nil
        :config
        (setq org-agenda-prefix-format '((agenda . " %i %?-12t% s")
                                         (todo . " %i %-12:c")
                                         (tags . " %i %-12:c")
                                         (search . " %i %-12:c"))))
    #+end_src

    The =org-agenda-prefix-format= is taken from [[https://github.com/m-cat/init.el/blob/master/init.el#L2082][m-cat's init.el]] and
    removes file name and category. No need to see the file name as
    everything is in the same file.

    #+begin_src emacs-lisp
      (use-package org-super-agenda
        :config
        (setq org-super-agenda-groups
              '((:name "Idag"
                       :time-grid t)
                (:name "Avakta" :todo "WAIT" :order 100)
                (:name "Tid över" :priority "C" :order 50)
                (:name "Låg prio" :priority "B" :order 50)
                (:name "Hög prio" :priority "A" :order 1)
                (:name "Att göra" :todo "TODO")
                (:name "Klart" :todo ("DONE" "CANCELLED") :order 200)
              ))
        (org-super-agenda-mode)
        :pin melpa)
    #+end_src
    Use pretty bullet points instead of asterix
    #+begin_src emacs-lisp
      (use-package org-bullets
        :after (org)
        :init
        (add-hook 'org-mode-hook
                  (lambda ()
                    (org-bullets-mode t)))
        :pin melpa-stable)
    #+end_src

    *NOTE:*
    "Doesn't work with yasnippet getting:
     yas--fallback: yasnippet fallback loop!"

    This can happen when you bind ‘yas-expand’ outside of the ‘yas-minor-mode-map’.

*** Buffer move
    Move buffers around between windows
    #+begin_src emacs-lisp
      (use-package buffer-move
        :bind ( ("<M-S-up>"    . buf-move-up)
                ("<M-S-down>"  . buf-move-down)
                ("<M-S-left>"  . buf-move-left)
                ("<M-S-right>" . buf-move-right))
        :pin melpa-stable)
    #+end_src
*** Dired
    Settings for dired.
    Source for the afs-dired-find-file function: [[https://stackoverflow.com/questions/1110118/in-emacs-dired-how-to-find-visit-multiple-files][Source]]
    #+begin_src emacs-lisp
      (use-package dired
       	:ensure nil
       	;; Map afs-dired-find-file to F
       	:bind (:map dired-mode-map
               ("F" . afs-dired-find-file))
       	:config
       	(defun afs-dired-find-file (&optional arg)
             "Open each of the marked files, or the file under the
           point, or when prefix arg, the next N files "
             (interactive "P")
             (let ((fn-list (dired-get-marked-files nil arg)))
               (mapc 'find-file fn-list))))
    #+end_src
*** Diff

    Enable whitespace mode for diff-mode to see trailing whitespace in
    diffs.
    #+begin_src emacs-lisp
      (use-package whitespace
        :ensure nil
        :hook (diff-mode . whitespace-mode))
    #+end_src

    #+begin_src emacs-lisp
      (use-package diff
        :ensure nil
        :config
        (add-hook 'diff-mode-hook 'dotemacs-hide-trailing-whitespace))
    #+end_src
*** Ediff
    #+begin_src emacs-lisp
      (use-package ediff
        :ensure nil
        :config
        (setf ediff-window-setup-function 'ediff-setup-windows-plain))
    #+end_src
*** Eshell
    Using some eshell settings from [[https://github.com/howardabrams/dot-files/blob/master/emacs-eshell.org][Howard Abrams]].

    #+begin_src emacs-lisp
      (use-package eshell
        :config
        (setq-default
         eshell-prompt-function
         (lambda ()
           (let* ((pwd (eshell/pwd))
                  (remote (file-remote-p pwd))
                  (remote-name (when remote (cadr (split-string remote ":")))))
             (format "⎣%s%s%s %s⎦ "
               (propertize (user-login-name) 'face '(:foreground "#3387cc"))
               (propertize "@" 'face `(:foreground ,(if remote "#f9fd75" "#ddd")))
               (propertize (or remote-name (system-name)) 'face '(:foreground "#ddd"))
               (propertize (file-name-base
                            (abbreviate-file-name
                             (if remote (string-remove-prefix remote pwd) pwd)))
                           'face '(:foreground "#666")))))
         eshell-highlight-prompt nil
         eshell-prompt-regexp "^⎣.*⎦ "
         ;; eshell-buffer-shorthand t ...  Can't see Bug#19391
         eshell-scroll-to-bottom-on-input 'all
         eshell-error-if-no-glob t
         eshell-hist-ignoredups t
         eshell-save-history-on-exit t
         eshell-prefer-lisp-functions nil
         eshell-destroy-buffer-when-process-dies t
         eshell-cmpl-cycle-completions nil)
        (add-hook 'eshell-mode-hook 'dotemacs-hide-trailing-whitespace)
        (add-hook
         'eshell-mode-hook
         (lambda ()
           (eshell/alias "ff" "find-file $1")
           (eshell/alias "ffw" "find-file-other-window $1")
           (eshell/alias "fff" "find-file-other-frame $1")))
        ;; Cannot use :bind to set keys for some reason
        ;; Make up and down navigate the buffer, similar to shell.
        ;; And jump betwen prompts with C-M-{p,n}
        (add-hook 'eshell-mode-hook
                  (lambda ()
                    (mapc (lambda (key)
                            (define-key eshell-mode-map key nil))
                          '([up] [C-up] [down] [C-down]))
                    (define-key eshell-mode-map (kbd "C-M-p") 'eshell-previous-prompt)
                    (define-key eshell-mode-map (kbd "C-M-n") 'eshell-next-prompt))))
    #+end_src

    #+begin_src emacs-lisp
      (defun eshell/lcd (&optional directory)
        "Locally cd to a DIRECTORY when on a remote host."
        (if (file-remote-p default-directory)
            (with-parsed-tramp-file-name default-directory nil
              (eshell/cd (tramp-make-tramp-file-name
                          (tramp-file-name-method v)
                          (tramp-file-name-user v)
                          (tramp-file-name-host v)
                          (or directory "")
                          (tramp-file-name-hop v))))
          (eshell/cd directory)))
    #+end_src
    Function taken from this [[https://www.reddit.com/r/emacs/comments/5pziif/cd_to_home_directory_of_server_when_using_eshell/de9olb7][reddit answer]]
*** Eldoc
    #+begin_src emacs-lisp
      (use-package eldoc
        :ensure nil
        :diminish t
        :config
        (setf eldoc-echo-area-use-multiline-p nil))
    #+end_src
*** emms
    Using Arch's package manager to handle emms, as I need the
    emms-print-metadata function for libtag.
    #+begin_src emacs-lisp
      (use-package emms
        :ensure nil
        :if (not dotemacs-is-work)
        :bind
        (("<f7>" . emms)
         ("<C-f7>" . emms-browser)
         ("<XF86AudioPrev>" . emms-previous)
         ("<XF86AudioNext>" . emms-next)
         ("<XF86AudioPlay>" . emms-pause)
         ("<XF86AudioStop>" . emms-stop))
        :config
        (require 'emms-setup)
        (require 'emms-info-libtag)
        (emms-all)
        (setq emms-source-file-default-directory "/media/Valhalla/Music/"
              emms-source-file-directory-tree-function 'emms-source-file-directory-tree-find
              emms-player-list '(emms-player-mpv)
              emms-info-functions '(emms-info-libtag)))
    #+end_src
*** ibuffer
     Use ibuffer instead of list-buffers, has some neat features.

     Sort buffers by placing them in different groups. Hide empty
     groups to avoid cluttering the ibuffer.
     #+begin_src emacs-lisp
       (use-package ibuffer
         :config
         (defalias 'list-buffers 'ibuffer)
         (setq-default ibuffer-expert t ;; Don't ask when closing unmodified buffers
                       ibuffer-show-empty-filter-groups nil)
         (setq ibuffer-saved-filter-groups
               '(("default"
                  ("c++" (mode . c++-mode))
                  ("make"  (or (mode . makefile-gmake-mode)
                               (mode . makefile-mode)))
                  ("cmake" (mode . cmake-mode ))
                  ("scripts" (mode . sh-mode))
                  ("ag" (mode . ag-mode ))
                  ("ivy" (name . "^\\*ivy-.*$"))
                  ("docs" (or (mode . rst-mode)
                              (mode . Man-mode)
                              (mode . markdown-mode)
                              (mode . org-mode)))
                  ("dired" (mode . dired-mode))
                  ("python" (mode . python-mode))
                  ("yaml" (mode . yaml-mode))
                  ("json" (mode . json-mode))
                  ("jinja" (mode . jinja2-mode))
                  ("vc" (or (mode . vc-dir-mode)
                            (mode . diff-mode)
                            (mode . magit--turn-on-shift-select-mode)
                            (mode . magit-auto-revert-mode)
                            (mode . magit-blame-disable-mode)
                            (mode . magit-blame-disabled-mode)
                            (mode . magit-blame-mode)
                            (mode . magit-blame-put-keymap-before-view-mode)
                            (mode . magit-blob-mode)
                            (mode . magit-cherry-mode)
                            (mode . magit-diff-mode)
                            (mode . magit-file-mode)
                            (mode . magit-log-mode)
                            (mode . magit-log-select-mode)
                            (mode . magit-merge-preview-mode)
                            (mode . magit-popup-mode)
                            (mode . magit-process-mode)
                            (mode . magit-process-unset-mode)
                            (mode . magit-reflog-mode)
                            (mode . magit-refs-mode)
                            (mode . magit-repolist-mode)
                            (mode . magit-revision-mode)
                            (mode . magit-stash-mode)
                            (mode . magit-stashes-mode)
                            (mode . magit-status-mode)
                            (mode . magit-submodule-list-mode)
                            (mode . magit-turn-on-auto-revert-mode)
                            (mode . magit-wip-after-apply-mode)
                            (mode . magit-wip-after-save-local-mode)
                            (mode . magit-wip-after-save-mode)
                            (mode . magit-wip-before-change-mode)))
                  ("shell" (mode . shell-mode))
                  ("gdb" (mode . gdb-script-mode))
                  ("elisp" (mode . emacs-lisp-mode))
                  ("emacs" (name . "^\\*.*?\\*$")))))
       (add-hook 'ibuffer-mode-hook
                 (lambda ()
                   ;; Sucks up a lot of cpu time when using projectile
                   ;;(ibuffer-auto-mode 1) ;; Keep the ibuffer in sync
                   (ibuffer-switch-to-saved-filter-groups "default"))))
     #+end_src
*** ivy
    Better multi-editing than ag.el.
    See [[https://sam217pa.github.io/2016/09/11/nuclear-power-editing-via-ivy-and-ag/][nuclear weapon multi-editing]]

    #+begin_src emacs-lisp
      (use-package ivy
        :config
        (setq ivy-count-format "(%d/%d) ")
        :pin melpa)
    #+end_src

    Use counsel-imenu instead of imenu. To avoid hunting down all
    keymaps that defines imenu, easier to just alias the function.
    #+begin_src emacs-lisp
      (use-package counsel
        :bind (("C-M-s" . counsel-ag))
        :init
        (defalias 'imenu 'counsel-imenu)
        :pin melpa)
    #+end_src

    #+begin_src emacs-lisp
      (use-package wgrep
        :pin melpa-stable)
    #+end_src
*** info
    #+begin_src emacs-lisp
      (use-package info
        :ensure nil
        :config
        (add-hook 'Info-mode-hook 'dotemacs-hide-trailing-whitespace))
    #+end_src
*** Tramp
    Set the ssh to be the default method for tramp.
    If tramp hangs and you are using zsh see [[#tramp-hang-workaround][here]].
    #+begin_src emacs-lisp
      (use-package tramp
        :config
        (setq tramp-default-method "ssh"
              tramp-ssh-controlmaster-options
               (concat
                "-o ControlPath=/tmp/ssh-tramp-ControlPath-%%r@%%h:%%p "
                "-o ControlMaster=auto -o ControlPersist=yes"))
        ;; Deal with work, guix and my custom scripts
        (add-to-list 'tramp-remote-path "~/bin")
        (add-to-list 'tramp-remote-path "/tools/bin")
        (add-to-list 'tramp-remote-path "~/.guix-profile/bin")
        (add-to-list 'tramp-remote-path "~/.guix-profile/sbin")
        (add-to-list 'tramp-remote-path "/run/current-system/profile/bin")
        (add-to-list 'tramp-remote-path "/run/current-system/profile/sbin")
        :pin gnu)
    #+end_src
*** Sudo edit
    Sudo edit the current file
    #+begin_src emacs-lisp
      (use-package sudo-edit
       	:bind ("C-c C-r" . sudo-edit)
       	:pin melpa)
    #+end_src
*** Windmove
    Jump between windows using the arrow keys instead of cycling with
    "C-x o". Note that this Doesn't work in org mode.

    *TIP:* If using i3wm. Use frames instead of windows then use i3's
     navigation instead.
    #+begin_src emacs-lisp
      (use-package windmove
        :bind (([M-left]  . windmove-left)  ; move to left window
               ([M-right] . windmove-right) ; move to right window
               ([M-up]    . windmove-up)    ; move to upper window
               ([M-down]  . windmove-down)) ; move to downer window
        :pin melpa-stable)
    #+end_src
*** Compilation
    Ansi colors in compilation window see [[https://stackoverflow.com/questions/13397737/ansi-coloring-in-compilation-mode][link]]

    Have disabled automatically closing the *compilation* buffer if no
    errors occur. For one the function in [[https://www.emacswiki.org/emacs/ModeCompile#toc2][link]] doesn't properly swap
    to the correct buffer. Usually you end up with multiple frames
    having the same buffer open, which is annoying.

    Second it will close the buffer if only warnings occured. I like
    to have my code warning free and thus I need to see if any
    warnings occured. And cannot force all warnings to be treated as
    errors as others might not share the same idea about warnings.

    #+begin_src emacs-lisp
      (use-package compile
        :init
        ;; Reuse the *compilaiton* window if open if not pick another window
        ;; in another frame.
        (add-to-list 'display-buffer-alist
                     '("^\\*compilation\\*$"
                       (display-buffer-reuse-window display-buffer-use-some-frame)
                       (reusable-frames      . visible)
                       (inhibit-switch-frame . t)
                       (inhibit-same-window  . t)
                       ))
        :config
        (use-package ansi-color)
        (setf compilation-scroll-output t)
        (add-hook 'compilation-filter-hook
                  (lambda ()
                    (toggle-read-only)
                    (ansi-color-apply-on-region compilation-filter-start (point))
                    (toggle-read-only))))
    #+end_src
*** Version Control
    Don't ask when following a symlink to a vc directory.
    #+begin_src emacs-lisp
      (setq vc-follow-symlinks t)
    #+end_src
*** Regexp builder
    Avoid escape-hell with regex builder, can toggle between styles
    with 'C-c <tab>'. See [[https://masteringemacs.org/article/re-builder-interactive-regexp-builder][masteringemacs]] for more info about regex
    builder.

    #+begin_src emacs-lisp
      (use-package re-builder
        :config
        (setq-default reb-re-syntax 'string))
    #+end_src
*** evil
    Vim bindings are a lot easier to use on the phone than normal
    emacs bindings. Enable *evil-mode* when it detects android.
    #+begin_src emacs-lisp
      (use-package evil
        :if (getenv "ANDROID_ROOT")
        :bind (:map evil-normal-state-map ("SPC t" . 'training-popup))
        :config
        (evil-mode 1)
        :pin melpa-stable)
    #+end_src
*** elfeed
    #+begin_src emacs-lisp
      (defun plt/elfeed-youtube-feeds (feeds)
        "Process FEEDS and return a list of youtube feeds.
      Where the layout of FEEDS is '((NAME CHANNEL-ID TAGS...)...)"
        (let ((yt-prefix "https://www.youtube.com/feeds/videos.xml?channel_id="))
          (--map `(,(s-prepend yt-prefix (cadr it)) youtube ,@(cddr it)) feeds)))
    #+end_src

    RSS reeder
    #+begin_src emacs-lisp
      (use-package elfeed
        :bind (("C-c n" . 'elfeed)
               :map elfeed-search-mode-map
               ;; Use similar bindings as notmuch
               ("l" . 'elfeed-search-untag-all-unread)
               ("o" . 'elfeed-search-tag-all-unread)
               ("t" . (lambda ()
                        (interactive)
                        (-each (elfeed-search-selected)
                          (lambda (entry)
                            (if (member 'later (elfeed-entry-tags entry))
                                (elfeed-untag entry 'later)
                              (elfeed-tag entry 'later))
                            (elfeed-search-update-entry entry)))))
               ;; Mark all as read
               ("L" . (lambda ()
                        (interactive)
                        (mark-whole-buffer)
                        (elfeed-search-untag-all-unread)))
               ;; Mark all as unread
               ("O" . (lambda ()
                  (interactive)
                  (mark-whole-buffer)
                  (elfeed-search-tag-all-unread)))
               ("v" . plt/elfeed-view-mpv)
               )
        :config
        (add-hook 'elfeed-show-mode-hook 'dotemacs-hide-trailing-whitespace)
        (add-hook 'elfeed-search-mode-hook 'dotemacs-hide-trailing-whitespace)
        (add-hook 'elfeed-new-entry-hook
                  (elfeed-make-tagger :before "1 week ago"
                                      :remove 'unread))
        (setf elfeed-feeds
              `(("https://rebusinla.wordpress.com/feed/" fun blog)
                ("https://warpdrive.se/rss/" fun)
                ("https://xkcd.com/atom.xml" fun)
                ("https://c0de517e.blogspot.com/feeds/posts/default" cg)
                ("https://animationphysics.wordpress.com/feed/"  cg)
                ("https://www.realtimerendering.com/blog/feed/" cg blog)
                ("https://www.vfxblog.com/feed/" cg)
                ("https://www.fz.se/rss/fznews_rss20.xml" news)
                ("https://rss.slashdot.org/Slashdot/slashdot" news)
                ("https://www.reddit.com/r/MechGroupBuys/.rss" keebs)
                ("https://www.reddit.com/r/emacs/.rss" emacs)
                ("https://www.reddit.com/r/MechanicalKeyboards/.rss" keebs)
                ("https://www.engadget.com/rss.xml" news)
                ("https://www.anandtech.com/rss/" news nerd)
                ("https://www.macrumors.com/macrumors.xml" news)
                ("https://www.sweclockers.com/feeds/news.xml" news nerd)
                ("https://www.raspberrypi.org/feed" news)
                ("https://lwn.net/headlines/newrss" news linux)
                ("https://feeds.arstechnica.com/arstechnica/index/" news nerd)
                ("https://www.phoronix.com/rss.php" news linux)
                ("https://feeds.feedburner.com/TheHackersNews" news nerd)
                ("https://www.gnu.org/software/guix/feeds/blog.atom" blog linux)
                ("https://www.linuxjournal.com/node/feed" linux)
                ("https://www.reddit.com/r/ErgoMechKeyboards/.rss" keebs)
                ("https://www.dpreview.com/feeds/news.xml" photo)
                ("https://nikonrumors.com/feed" photo)
                ("https://www.archlinux.org/feeds/news/" linux)
                ,@(plt/elfeed-youtube-feeds
                   '(("Avatar" "UCyaPf0E-PRRZH3UvvxNPeEw" music)
                     ("Blackbriar" "UCjR-qXRBNkysQ0Threo1Bfg" music)
                     ("Cppcon" "UCMlGfpWw-RUdWX_JbLCukXg" talks)
                     ("Fosdem" "UC9NuJImUbaSNKiwF2bdSfAw" talks)
                     ("Gamers Nexus" "UChIs72whgZI9w6d6FhwGGHA" news nerd)
                     ("Ghost" "UCAOiVaJJlH0Oduv48NN0mMA" music)
                     ("HackersOnBoard" "UChGDEluRG9r5kCecRAQTx_Q" talks)
                     ("Infidelamsterdam" "UCTp0MnlTlmqC3NdrPzD08EA" news vlog)
                     ("Intermit.Tech" "UCv7UOhZ2XuPwm9SN5oJsCjA" news vlog)
                     ("Knyght Errant" "UC1T4KJG1L_kTrP9RcdU5Csw" history)
                     ("Level1Linux" "UCOWcZ6Wicl-1N34H0zZe38w" linux)
                     ("Level1Techs" "UC4w1YQAJMWOz4qtxinq55LQ" nerd)
                     ("Lindybeige" "UC9pgQfOXRsp4UKrI8q0zjXQ" history)
                     ("Mark Furneaux" "UCRDQEDxAVuxcsyeEoOpSoRA" nerd)
                     ("Matgeek" "UCSGHj0YjencmGUSksbMbBVQ" food)
                     ("Orbit Culture" "UC2XMr58U7rZnL4AW0n9Ca8g" music)
                     ("Paul's Hardware" "UCvWWf-LYjaujE50iYai8WgQ" news nerd)
                     ("Sabaton" "UCjQhd1APsd5NQhiVZV7GYzg" music)
                     ("Sabaton History" "UCaG4CBbZih6nLzD08bTBGfw" history)
                     ("Skallagrim" "UC3WIohkLkH4GFoMrrWVZZFA" history)
                     ("Sweclockers" "UCW64r1wPzfj0W1qbzzfCgFg" news nerd)
                     ("Sweclockers Extra" "UCfK96bDQdSkKFAdqNv0YOmw" nerd fun)
                     ("The Hu" "UCs6vRDdkZ8bP8Xt6WHbvrwA" music)
                     ("Nuclear Blast Records" "UCoxg3Kml41wE3IPq-PC-LQw" music)
                     ("Century Media Records" "UCnK9PxMozTYs8ELOvgMNKFA" music)
                     ("Metal Blade Records" "UCSldglor1t-5E-Gy2eBdMrA" music)
                     ("DistroTube" "UCVls1GmFKf6WlTraIb_IaJg" linux)
                     ("A&P Reacts" "UC0NpEEcmONWuTU3nfURmyKw" music)
                     ))
                )))
    #+end_src

    Functions based on the blog entry at [[https://joshrollinswrites.com/help-desk-head-desk/20200611/][joshrollinswrites.com]]. But made some
    small changes to open up multiple videos with one mpv window.

    #+begin_src emacs-lisp
      (defun plt/elfeed-mpv (urls)
        "Watch videos from URLS in mpv."
        (async-shell-command (s-join " " `("mpv" ,@(--map (format "%S" it) urls)))))

      ;; Don't show the async buffer
      (add-to-list 'display-buffer-alist
                   '("^\\*Async Shell Command\\*$"
                     (display-buffer-no-window)))

      (defun plt/elfeed-view-mpv ()
        "Grab youtube-feed links."
        (interactive)
        (let ((entries (elfeed-search-selected)))
          (->> entries
               (-map #'elfeed-entry-link)
               -non-nil
               plt/elfeed-mpv)
          (-each entries
            (lambda (entry)
              (elfeed-untag entry 'unread)
              (elfeed-search-update-entry entry))))
        (unless (use-region-p) (forward-line)))
    #+end_src
** Text
  Packages for editing and viewing text.
*** Emojify

    Need to be able to render emojis properly when reading emails. And
    since emacs in Linux doesn't support Color fonts (yet?) needed for
    it to work with Google's Noto Emoij font. MacOS had support but
    got removed in [[https://github.com/emacs-mirror/emacs/blob/emacs-25.1/etc/NEWS#L1723][25.1]].

    I'll need to use emojify instead.

    #+begin_src emacs-lisp
      (use-package emojify
        :after (notmuch)
        :init
        ;; Enable emojify when searching and reading emails
        (add-hook 'notmuch-search-mode-hook 'emojify-mode)
        (add-hook 'notmuch-show-mode-hook 'emojify-mode)
        (add-hook 'notmuch-message-mode-hook 'emojify-mode)
        :pin melpa-stable)
    #+end_src
*** Rainbow
    Useful when debugging the theme. But is rarely used.
    #+begin_src emacs-lisp
      (use-package rainbow-mode
       	:pin gnu)
    #+end_src
*** Move text
    Move line up and down using arrow keys.
    #+begin_src emacs-lisp
      (use-package move-text
       	:bind (([C-S-up] . move-text-up)
               ([C-S-down] . move-text-down))
       	:pin melpa-stable)
    #+end_src

*** Expand region
    #+begin_src emacs-lisp
      (use-package expand-region
       	:bind ("C-=" . er/expand-region)
       	:pin melpa-stable)
    #+end_src
*** Multiple cursors
    Keybindings for the mc package
    #+begin_src emacs-lisp
      (use-package multiple-cursors
        :bind (("C-S-c C-S-c" . mc/edit-lines)
               ("C->"         . mc/mark-next-like-this)
               ("C-<"         . mc/mark-previous-like-this)
               ("C-c C-<"     . mc/mark-all-like-this)
               ("C-+"         . mc/mark-next-like-this)
               :map mc/keymap
               ("C-c m n"     . mc/insert-numbers)
               ("C-c m c"     . mc/insert-characters)
               ("C-c m s n"   . mc/insert-same-numbers-per-line)
               ("C-c m s c"   . mc/insert-same-chars-per-line))
        :config
        :pin melpa-stable)
    #+end_src

    #+begin_src emacs-lisp
      (use-package mc-extras
        :after (multiple-cursors)
        :pin melpa-stable)
    #+end_src
*** String inflections
    Keybinding for cycle between snake case, camel case etc
    #+begin_src emacs-lisp
      (use-package string-inflection
       	:bind ("C-;" . string-inflection-cycle)
       	:pin melpa-stable)
    #+end_src
*** Abbrev
    #+begin_src emacs-lisp
      (diminish 'abbrev-mode)
    #+end_src

*** isearch

    Integrate packages as expand-region with isearch. This function
    comes from issue [[https://github.com/magnars/expand-region.el/issues/17][#17]] on expand-region.el.
    #+begin_src emacs-lisp
      (use-package isearch
        :ensure nil
        :config
        (defun isearch-yank-selection ()
        "Put selection from buffer into search string."
        (interactive)
        (when (region-active-p)
          (deactivate-mark))  ;;fully optional, but I don't like unnecesary highlighting
        (isearch-yank-internal (lambda () (mark))))
        :bind (:map isearch-mode-map ("C-o" . isearch-yank-selection)))
    #+end_src
** Nov
   Epub reader mode.
   #+begin_src emacs-lisp
     (use-package nov
       :mode (("\\.epub\\'" . nov-mode))
       :pin melpa-stable)
   #+end_src
** Shell
   Enable color in shell and define the color theme. Also disable
   yasnippet in shell mode since that's messing with the shell.

   Disabled the comint-highlight-prompt to use the colors from the
   shells prompt. Source: [[https://stackoverflow.com/questions/25819034/colors-in-emacs-shell-prompt][link]].

   Custom function to clear the shell in emacs. Bound to f8. Also
   works for gdb.

   Always use bash as the backend for the shell as not every machine
   has zsh.

   #+begin_src emacs-lisp
     (use-package shell
       :bind ("<f8>" . clear-shell)
       :init
       (setenv "ESHELL" "bash")
       :config
       ;; Use the prompts colours instead of ansi-color
       (set-face-attribute 'comint-highlight-prompt nil
                           :inherit nil)
       (add-hook 'shell-mode-hook
                 (lambda ()
                   ;; Enable color in shell
                   (ansi-color-for-comint-mode-on)
                   ;; Change Color theme in shell
                   (setq ansi-color-names-vector
                         ["#4d4d4d"
                          "#D81860"
                          "#60FF60"
                          "#f9fd75"
                          "#4695c8"
                          "#a78edb"
                          "#43afce"
                          "#f3ebe2"])
                   (setq ansi-color-map (ansi-color-make-color-map))
                   ;; Disable yas minor mode
                   (yas-minor-mode -1)
                   ;; Add go and goc to the dirtrack, Need tweak the regexp
                   ;; (setq shell-cd-regexp "\\(cd\\|goc\\|go\\)")
                   ))
       ;; Easier keybinding for jumping between prompts
       (add-hook 'shell-mode-hook
                 (lambda ()
                   (define-key comint-mode-map (kbd "C-M-p") 'comint-previous-prompt)
                   (define-key comint-mode-map (kbd "C-M-n") 'comint-next-prompt)))
       (defun clear-shell ()
         "Clear the shell buffer"
         (interactive)
         (let ((comint-buffer-maximum-size 0))
           (comint-truncate-buffer))))
   #+end_src
** guix
   #+begin_src emacs-lisp
     (when dotemacs-guix-installed
       (use-package guix
         :ensure nil
         :bind ("<f3>" . guix)
         :pin melpa-stable))
   #+end_src
* Custom
** Packages
*** home
    #+begin_src emacs-lisp
      (use-package home
        :ensure nil
        :load-path "plugins")
    #+end_src
*** bfuture
    #+begin_src emacs-lisp
      (use-package bfuture
        :ensure nil
        :load-path "bfuture.el")
    #+end_src
*** bank
    Functions for handling bank statements
    #+begin_src emacs-lisp
      (use-package bank
        :ensure nil
        :load-path "plugins")
    #+end_src
*** Multiple cursor extension
    Add some extra functionality to multiple cursors inserting numbers
    and characters.
    #+begin_src emacs-lisp
      (use-package mc-extra-extra
        :after (multiple-cursors)
        :ensure nil
        :load-path "plugins")
    #+end_src
*** newfile
    Functions for setting up a newfile in c++. I.e create the license
    boilerplate, add the include guard, header for the author etc and
    namespaces based on directory structure.
    #+begin_src emacs-lisp
      (use-package newfile
        :ensure nil
        :load-path "plugins")
    #+end_src
*** cpreproc
    Functions to help with c/c++ development
    #+begin_src emacs-lisp
      (use-package cpreproc
        :ensure nil
        :load-path "plugins")
    #+end_src
*** training
    Functions for using ledger as a training log.
    #+begin_src emacs-lisp
      (use-package training
        :ensure nil
        :load-path "plugins")
    #+end_src
** Functions
*** Buffer
**** Rename current file or buffer
     Function for renaming buffer and file. [[http://www.stringify.com/2006/apr/24/rename/][Source]]
     #+begin_src emacs-lisp
      (defun rename-current-file-or-buffer ()
        "Rename current file and buffer, similar to save-as but removes
      the old file"
        (interactive)
        (if (not (buffer-file-name))
            (call-interactively 'rename-buffer)
          (let ((file (buffer-file-name)))
            (with-temp-buffer
              (set-buffer (dired-noselect file))
              (dired-do-rename)
              (kill-buffer nil))))
        nil)
     #+end_src
**** Revert all buffers
    To sync all open buffers with their respective files on disk.
    Based on [[https://www.emacswiki.org/emacs/RevertBuffer][link]] but skips buffers which file no longer exist.
    #+begin_src emacs-lisp
        (defun revert-all-buffers ()
            "Refreshes all open buffers from their respective files."
            (interactive)
            (dolist (buf (buffer-list))
              (with-current-buffer buf
                (when (and (buffer-file-name)
                           (not (buffer-modified-p))
                           (file-exists-p (buffer-file-name)))
                  (revert-buffer t t t) )))
            (message "Refreshed open files."))
    #+end_src
**** ibuffer filters
    Similar to projectile's ibuffer filter. Except this isn't locked
    to the project root.
    #+begin_src emacs-lisp
      (defun ibuffer-at-directory (dir)
        "Open an ibuffer with buffers containg files with matching prefix DIR."
        (interactive "DDirectory to filter on: ")
        (ibuffer t (format "*%s-buffers*" dir) (list (cons 'directory dir))))
    #+end_src

    List all buffers which file no longer exist.
    #+begin_src emacs-lisp
      (use-package ibuf-ext
        :ensure nil
        :after (ibuffer)
        :config
        (define-ibuffer-filter dangling-buffer
            "True if buffer is visiting a file but the file no longer exist."
          (:reader nil :description "dangling-buffer")
          (with-current-buffer buf
            (and (buffer-file-name)
                 (not (file-exists-p (buffer-file-name))))))
        (defun ibuffer-dangling-buffers ()
          (interactive)
          "Open an ibuffer with buffers which file no longer exist."

          (ibuffer t "*dangling-buffers*" (list (cons 'dangling-buffer "")))))
    #+end_src
*** Text
    #+begin_src emacs-lisp
      (defun duplicate-line()
        "Clone line and paste it below."
        (interactive)
        (let ((line (buffer-substring (point-at-bol) (point-at-eol)))
              (current (point)))
          (goto-char (point-at-eol))
          (insert "\n" line)
          (goto-char current)))
    #+end_src
**** Format

     Different functions to quickly format text.
     #+begin_src emacs-lisp
       (defun fmt-parens-loosen (start end)
         "Add a space between parens and content for the region START END.

       e.g. (foo) -> ( foo ).

       It will not expand () by default. Use prefix to include it.

       When using this interactive it will pick the region from current
       point to the end of the buffer. If a region is active it will
       pick that instead."

         (interactive (if (region-active-p)
                          (list (region-beginning) (region-end))
                        (list (point) (point-max))))
         (let ((regexp
                (if (not current-prefix-arg)
                    ;; Ignore ()
                    "\\(?:\\(?1:(\\)\\(?2:[^ \n)]\\)\\|\\(?1:[^ (]\\)\\(?2:)\\)\\)"
                  ;; Include ()
                  "\\(?:\\(?1:(\\)\\(?2:[^ \n]\\)\\|\\(?1:[^ ]\\)\\(?2:)\\)\\)")))
           (fmt-replace-regexp regexp "\\1 \\2" start end)))
     #+end_src

     #+begin_src emacs-lisp
       (defun fmt-parens-tighten (start end)
         "Remove spaces between parens and content inside START and END.

       e.g. (  foo ) -> (foo)

       When using this interactive it will pick the region from current
       point to the end of the buffer. If a region is active it will
       pick that instead."
         (interactive (if (region-active-p)
                   (list (region-beginning) (region-end))
                 (list (point) (point-max))))
         (let ((regex "\\(?:\\(?1:(\\)[ ]+\\(?2:[^ ]\\)\\|\\(?1:[^ ]\\)[ ]+\\(?2:)\\)\\)"))
           (fmt-replace-regexp regex "\\1\\2" start end)))
     #+end_src

     #+begin_src emacs-lisp
       (defun fmt-one-space-after-comma (start end)
         "Make sure there is just one space after comma inside START and END.

       e.g. foo(bar,baz,  boo) -> foo(bar, baz, boo).

       When using this interactive it will pick the region from current
       point to the end of the buffer. If a region is active it will
       pick that instead."
         (interactive (if (region-active-p)
                   (list (region-beginning) (region-end))
                 (list (point) (point-max))))
         (my-replace-regexp "\\(?:\\(?1:,\\)[ ]*\\(?2:[^ \n]\\)\\)" "\\1 \\2" start end))
     #+end_src

     #+begin_src emacs-lisp
       (defun fmt-replace-regexp (regexp to-string start end)
         "Replace everything matching REGEXP with TO-STRING from START to END.

       This is similar to `replace-regexp' but using `re-search-forward'
       and `replace-match'."
         (save-excursion
           (goto-char start)
           (while (re-search-forward regexp end t)
             (let ((current-point (point)))
               (replace-match to-string)
               ;; The end point will shift when replacing text in the buffer
               (setq end (+ end (- (point) current-point)))))))
     #+end_src
*** Programming
**** C++
***** Expands a define macro for all matches in current buffer.
      #+begin_src emacs-lisp
        (defun replace-define()
          "Evaluating the define variable.
        Place cursor on a #define <var> <content> and execute this command and it will
        replace all <var> with <content> in the file."
          (interactive)
          (let ((line (split-string (thing-at-point 'line) )))
                 (if (equal (car line) "#define")
                     (let ((curr-pos (point)) ;; save current position
                           (end (point-max)))
                  ;; Jump to the end of line
                  (end-of-line)
                  ;; Replace the first with the second.
                  (while (re-search-forward (concat "\\_<"(nth 1 line)"\\_>") end t )
                         (replace-match (nth 2 line)))
                  ;; return to the same position
                  (goto-char curr-pos)
                  ;; move to the end of the line to indicate that it's done.
                  (end-of-line))
                   (message "Not a #define directive!" ))))
      #+end_src
***** Undo replace-define.
       #+begin_src emacs-lisp
         (defun replace-define-undo()
           "Undoing the expansion of the define variable.
         Place cursor on a #define <var> <content> and execute this
          command and it will replace all <content> with <var> in the
          file."

           (interactive)
           (let ((line (split-string (thing-at-point 'line) )))
             (if (equal (car line) "#define")
                 (let ((curr-pos (point)) ;; save current position
                       (end (point-max)))
                   ;; Jump to the end of line
                   (end-of-line)

                   ;; Replace the second with the first
                   (while (re-search-forward (nth 2 line) end t ) (replace-match (nth 1 line)))

                   ;; return to the same position
                   (goto-char curr-pos)
                   ;; move to the end of the line to indicate that it's done.
                   (end-of-line))
               (message "Not a #define directive!" ))))

       	   #+end_src

***** Convert typedef to c++11's alias
       #+begin_src emacs-lisp
         (defun convert-typedef-to-using ()
           "Converts typedef statements to using statements"
           (interactive)
           (let ((begin) (end))
              (if (use-region-p)
                 (progn (setq begin (region-beginning) end (region-end)))
               (progn (setq begin (point) end nil)))
              (goto-char begin)
             (while (re-search-forward
                     (concat "typedef \\(\\(?:typename \\)*"
                             "[[:print:]]+?\\)[ \t]+\\([[:alnum:]_]+\\)[ ]*;" )
                     end t )
               (replace-match "using \\2 = \\1;"))))
       #+end_src
***** Insert ifdef clauses

      #+begin_src emacs-lisp
        (defun afs-insert-ifdef (macro &optional add-else ifndef)
          "Insert C preprocessor conditional #ifdef MACRO. To add an else
          clause set ADD-ELSE to t. To invert the ifdef to #ifndef MACRO
           set ifndef to t."
          (interactive "sName of macro: ")
          (let* ((start (if (use-region-p) (region-beginning) (point-at-bol)))
                 (end (if (use-region-p) (region-end) (point-at-eol)))
                 (text (delete-and-extract-region start end))
                 (defcmd (if ifndef "#ifndef" "#ifdef")))
            (insert (concat (format "%s %s\n%s\n" defcmd macro text)
                            (when add-else (format "#else\n%s\n" text))
                            "#endif"))
            ))
      #+end_src

      #+begin_src emacs-lisp
        (defun afs-insert-ifdef-else (macro)
          "Insert C prepocessor conditional #ifdef MACRO with an else clause.
        Wrapper for (afs-insert-ifdef MACRO t)"
          (interactive "sName of macro: ")
          (afs-insert-ifdef macro t))
      #+end_src

      #+begin_src emacs-lisp
        (defun afs-insert-ifndef (macro)
          "Insert C prepocessor conditional #ifndef MACRO."
          (interactive "sName of macro: ")
          (afs-insert-ifdef macro nil t))
      #+end_src

      #+begin_src emacs-lisp
        (defun afs-insert-ifndef-else (macro)
          "Insert C prepocessor conditional #ifndef MACRO."
          (interactive "sName of macro: ")
          (afs-insert-ifdef macro t t))
      #+end_src

***** Convert java style comment to doxygen
     #+begin_src emacs-lisp
       (defun convert-java-comment-to-doxygen ()
           "Convert java style comment to doxygen"
         (interactive)
         (let ((begin) (end))
           (if (use-region-p)
               (progn (setq begin (region-beginning) end (region-end)))
             (progn (setq begin (point) end nil)))
           (goto-char begin)
           (while (re-search-forward
                   "/\\*\\*\n[ ]+\\*\\(.*\\)\n[ ]+\\*/"
                   end t )
             (replace-match "///\\1"))))

     #+end_src
***** Jump between template header and implementation
      #+begin_src emacs-lisp
        (defun ff-extension-other-impl ()
          "Return name of the header or template file corresponding to the current file."
          (interactive)
          (let* ((pathname (or (ff-buffer-file-name) "/none.none"))
                 (directory (file-name-directory pathname))
                 (filename (file-name-nondirectory pathname))
                 (ext (s-replace "c" "h" (file-name-extension filename)))
                 (base (file-name-base filename)))
            (ff-get-file `(,directory)
                         (format "%s.%s"
                                 (if (s-ends-with? "-impl" base)
                                     (s-chop-suffix "-impl" base)
                                   (s-append "-impl" base))
                                 ext))))
      #+end_src

*** Split lines
    Function for splitting lines at specified character. Default is ','.
    #+begin_src emacs-lisp
      (defun split-at (&optional delim)
      "Split region/line at DELIM, if there are multiple matches it
      will split each one. DELIM will default to \",\" if no delim is
      given."
      (interactive "sSpecify delimiter: ")
      (when (or (string= delim "") (not delim)) (setq delim ","))
      (let ((start (if (use-region-p) (region-beginning) (point-at-bol)))
            (end (if (use-region-p) (region-end) (point-at-eol)))
            (regex delim))
        (goto-char start)

        (while (search-forward-regexp regex end t)
          (insert "\n")
          (setq end (1+ end)))
        (indent-region start end)
        (goto-char start)))

      (defun split-at-comma ()
      "wrapper for split-at for use with key command"
      (interactive)
      (split-at ","))
    #+end_src
*** Yesterday-time
    Computes the time 24 hours ago
    #+begin_src emacs-lisp
      (defun yesterday-time ()
      "Provide the date/time 24 hours before the time now in the format
      of `current-time'."
        (let* ((now-time (current-time))              ; get the time now
               (hi (car now-time))                    ; save off the high word
               (lo (car (cdr now-time)))              ; save off the low word
               (msecs (nth 2 now-time)))              ; save off the milliseconds

          (if (< lo 20864)                        ; if the low word is too small for subtracting
              (setq hi (- hi 2)  lo (+ lo 44672)) ; take 2 from the high word and add to the low
            (setq hi (- hi 1) lo (- lo 20864)))   ; else, add 86400 seconds (in two parts)

          (list hi lo msecs))) ; regurgitate the new values
    #+end_src
** Keybindings
*** Minor mode
   To better organize what my custom keys are and also easy see what
   they do. I wrapped them up into a minor mode. Can just run
   'describe-minor-mode' then plattfot-mode to get a quick list of
   them. Downside is that I lost a bit of structure in this file when
   reading.

   Time will tell if that was a smart idea or not.

   #+begin_src emacs-lisp
     (defvar plattfot-mode-map
       (let ((map (make-sparse-keymap)))
         ;; Navigation
         (define-key map (kbd "C-x f") 'find-file-at-point)
         ;; Text search
         ;; Rebinding the text search to the regex variants as
         ;; use those far more than the normal ones.
         (define-key map (kbd "C-s") 'isearch-forward-regexp)
         (define-key map (kbd "C-r") 'isearch-backward-regexp)
         (define-key map (kbd "C-S-s") 'isearch-forward-symbol-at-point)
         ;; Text edit
         (define-key map (kbd "M-r") 'replace-regexp)
         (define-key map (kbd "C-c l") 'duplicate-line)
         (define-key map (kbd "C-,") 'split-at-comma)
         ;; Buffer functions
         (define-key map (kbd "C-c r") 'revert-all-buffers)
         (define-key map (kbd "C-c R") 'rename-current-file-or-buffer)
         ;; Compile from current location and to re-run
         (define-key map (kbd "<f12>") 'compile)
         (define-key map (kbd "<f11>") 'recompile)
         ;; UI
         ;; Key bindings if I really need to see the menu and tool bar.
         (define-key map (kbd "C-<f5>") 'menu-bar-mode)
         (define-key map (kbd "C-<f6>") 'tool-bar-mode)

         ;; Scrolling
         (define-key map (kbd "<next>") (lambda () (interactive) (scroll-up-command 10)))
         (define-key map (kbd "<prior>") (lambda () (interactive) (scroll-down-command 10)))
         ;; Slow scrolling
         (define-key map (kbd "<C-next>") 'scroll-up-line)
         (define-key map (kbd "<C-prior>") 'scroll-down-line)
         ;; Jump almost the whole page
         (define-key map (kbd "<M-next>") 'scroll-up-command)
         (define-key map (kbd "<M-prior>") 'scroll-down-command)

         (define-key map (kbd "<C-M-next>") 'end-of-buffer)
         (define-key map (kbd "<C-M-prior>") 'beginning-of-buffer)

         (define-key map (kbd "C-.") 'repeat)
         map)
       "Custom keymap for `plattfot-mode'.")

     (defvar plattfot-comint-mode-map
       (let ((map (copy-keymap plattfot-mode-map)))
         ;; Avoid overloading M-r in comint mode as that is used for
         ;; fetching history.
         (define-key map (kbd "M-r") 'counsel-shell-history)
         map)
       "Custom keymap for `plattfot-comint-mode'.")

     (define-minor-mode plattfot-mode
       "Custom keybindings for plattfot:
     \\{plattfot-mode-map}"
       :version "3.0.0"
       :lighter nil
       :keymap plattfot-mode-map
       nil)

     (define-globalized-minor-mode plattfot-global-mode plattfot-mode
       (lambda () (plattfot-mode 1)))

     (define-minor-mode plattfot-comint-mode
       "Custom keybindings for plattfot that removes the replace-regex keybinding:
     \\{plattfot-comint-mode-map}"
       :version "3.0.0"
       :lighter nil
       :keymap plattfot-comint-mode-map
       nil)
     (provide 'plattfot)
   #+end_src

   Added that I need to press ctrl and the function key for the UI keys
   as I was hitting these accidentaly from time to time when running
   'compile' or 'recompile'. Due to how my keyboard is layed out. See
   my [[https://github.com/plattfot/qmk_firmware/tree/master/layouts/community/ergodox/plattfot][qmk fork]] for why that is.

   Reason for having three different modes is to be able to disable
   the 'M-r' keybinding for comint modes, eg. shell and gud-gdb. This
   was the cleanest way I could find doing this.

   #+begin_src emacs-lisp
     (use-package plattfot
       :init
       (plattfot-global-mode 1)
       ;; Change to the comint mode to get history search.
       (add-hook 'comint-mode-hook
                 (lambda ()
                   (plattfot-mode 0)
                   (plattfot-comint-mode 1)))
       (add-hook 'eshell-mode-hook
                 (lambda ()
                   (plattfot-mode 0)
                   (plattfot-comint-mode 1)))
       :ensure nil)
   #+end_src

*** Macros
     "Macro" to quickly open a file that is located on my machine at
     work. As I'm just inserting text I switched the real macro to just
     using insert instead.

     Updated it only bind the key when I'm in the minibuffer as I
     don't have any use for this outside of that scope.
     #+begin_src emacs-lisp
       (add-hook
        'minibuffer-setup-hook
        (lambda ()
          (define-key minibuffer-local-map (kbd "C-c B")
            (lambda ()
              (interactive)
              (insert "/-:pd-ws-he03.d2.com:/dd/dept/software/users/fredriks/swdevl")))))
     #+end_src
*** Registers
    Quickly jump to files by pressing C-x r j <register>
    Jump to my init file with 'e' and init directory with 'i'.
    #+begin_src emacs-lisp
      (set-register ?e (cons 'file (concat user-emacs-directory "init.el")))
      (set-register ?i (cons 'file (concat user-emacs-directory
                                           "init.d/configuration.org")))
    #+end_src
* Work
** Custom
*** Packages
**** dd-newfile
     Function that inserts the DD template for a new file
     #+begin_src emacs-lisp
       (use-package dd-newfile
         :after newfile
         :ensure nil
         :load-path "plugins")
     #+end_src
**** dd-log-parser
     Functions for parsing the =DD::Logger=
     #+begin_src emacs-lisp
       (use-package dd-log-parser
         :if dotemacs-is-work
         :ensure nil
         :load-path "plugins")
     #+end_src
**** dd-pybuild2
     #+begin_src emacs-lisp
       (use-package dd-pybuild2
         :if dotemacs-is-work
         :ensure nil
         :load-path "plugins")
     #+end_src
**** houdini
     Houdini related functions, mostly handle houdini versions.
     #+begin_src emacs-lisp
       (use-package houdini
         :bind ("C-x j" . hou-insert-version)
         :if dotemacs-is-work
         :ensure nil
         :load-path "plugins")
     #+end_src
**** highlight-extra
     Functions for highlighting my shells when building etc
     #+begin_src emacs-lisp
       (use-package highlight-extra
         :ensure nil
         :load-path "plugins")
     #+end_src
**** work

     Bunch of functions to setup my work area when at work.
     #+begin_src emacs-lisp
       (use-package work
         :if dotemacs-is-work
         :ensure nil
         :load-path "plugins")
     #+end_src
*** Functions
**** PID
     Functions for getting the pid and other useful stuff regarding
     PIDs.

     #+begin_src emacs-lisp
       (defun pid (regex &optional index newest)
         "Get the pid of the first command matching REGEX.
       If more than one is running it return the one at INDEX.  Where
       INDEX starts from 0 and up.  If NEWEST is t it will sort the
       commands based on elapsed time before picking one."
         (interactive)
         (when (not index) (setq index 0))
         (let ((ps_list (ps-match regex)))
           (car (nth index (if newest (sort-ps-time ps_list) ps_list)))))
     #+end_src

     #+begin_src emacs-lisp
       (defun ps-match (regex)
         "Call ps and return a list of info for each the command matching the REGEX.
       The list format is '(pid time ppid user comm), where time is the
       elisp time value and corresponds to the time and date the process
       was started."
         (let ((ps_list
                (mapcar
                 (lambda (x) (split-string x))
                 (cl-remove-if
                  'string-empty-p
                  (split-string
                   (shell-command-to-string
                    (concat "ps axo lstart,pid,ppid,user,comm | grep -e " regex))
                   "\n")))))
           (mapcar
            (lambda (x)
              (let ((proc (nthcdr 5 x))
                    (time (date-to-time (mapconcat 'identity (butlast x 4) " "))))
                (setq x (append (list (car proc) time) (cdr proc)))))
            ps_list)))
     #+end_src

     #+begin_src emacs-lisp
       (defun sort-ps-time (ps_list)
         "Sort the PS_LIST based on the timestamp.
       In ascending order."
         (seq-sort (lambda (a b) (not (time-less-p (cadr a) (cadr b)))) ps_list))
     #+end_src

**** PID Houdini
     Get the PID for houdini
     #+begin_src emacs-lisp
       (defun pid-houdini (&optional index newest)
         "Get the pid for houdini.

             If more than one is running it returns the one at INDEX.  Where
             INDEX starts from 0 and up.  If NEWEST is t, sort on elapsed time
             before picking one."

         (interactive)
         (when (not index) (setq index 0))
         (pid "houdini-bin" index newest))
     #+end_src
**** PID Maya
     #+begin_src emacs-lisp
       (defun pid-maya (&optional index newest)
         "Get the pid for maya.
       If more than one is running it returns the one at INDEX.  Where
       INDEX starts from 0 and up.  If NEWEST is t, sort on elapsed time
       before picking one."
         (interactive)
         (when (not index) (setq index 0))
         (pid "maya\\.bin" index newest))
     #+end_src
**** PID smeat
     #+begin_src emacs-lisp
       (defun pid-smeat (&optional index newest)
         "Get the pid for smeat.
       If more than one is running it returns the one at INDEX.  Where
       INDEX starts from 0 and up.  If NEWEST is t, sort on elapsed time
       before picking one."
         (interactive)
         (when (not index) (setq index 0))
         ;; the ^= is to ignore houdini/python commands e.g houdini --with smeat=...
         (pid "smeat(:?[^=]+|$$)" index newest))
     #+end_src
**** Attach Houdini
     Used with gdb, prints attach <pid of houdini> in the prompt.
     #+begin_src emacs-lisp
       (defun attach-houdini (&optional index)
         "Prints attach <pid> into the buffer.
       INDEX is use to select which one if there are multiple instances
       running, INDEX counts from 1."
         (interactive"p")

         ;; The default for index is one.
         (when (< index 1) (setq index 1))
         (insert (format "attach %s" (pid-houdini (- index 1)))))
     #+end_src

     #+begin_src emacs-lisp
       (defun attach-houdini-newest (&optional index)
         "Prints 'attach <pid>' into the buffer.

       INDEX is use to select which one if there are multiple instances
       running, INDEX counts from 1.  PIDs are sorted on elapsed time
       before one is selected to return the newest houdini instance."
         (interactive"p")

         ;; The default for index is one.
         (when (not index) (setq index 1))
         (when (< index 1) (setq index 1))
         (insert (format "attach %s" (pid-houdini (- index 1) t))))
     #+end_src
**** Attach Maya
     #+begin_src emacs-lisp
       (defun attach-maya (&optional index)
         "Prints attach <pid> into the buffer.
       INDEX is use to select which one if there are multiple instances
       running, INDEX counts from 1."
         (interactive"p")
         ;; The default for index is one.
         (when (< index 1) (setq index 1))
         (insert (concat "attach " (pid-maya index) )))
     #+end_src
**** Attach smeat
     #+begin_src emacs-lisp
       (defun attach-smeat (&optional index)
	 "Prints attach <pid> into the buffer.
       INDEX is use to select which one if there are multiple instances
       running, INDEX counts from 1."
	 (interactive"p")

	 ;; The default for index is one.
	 (when (< index 1) (setq index 1))
	 (insert (concat "attach " (pid-smeat (- index 1)) )))
     #+end_src
**** Kill Houdini
     #+begin_src emacs-lisp
       (defun kill-houdini ()
         "Kill houdini.
       If more than one houdini are running it will kill the
       first one in the ps list."
         (interactive)
         (shell-command (concat "kill -9 " (pid-houdini))))
     #+end_src
**** Kill Maya
     #+begin_src emacs-lisp
       (defun kill-maya ()
         "Kill maya.
       If more than one Maya process are running it will kill the
       first one in the ps list."
         (interactive)
         (shell-command (concat "kill -9 " (pid-maya))))
     #+end_src
**** Smeat abort
     Not quite working. But sends a signal to the smeat process to abort the sim.
     #+begin_src emacs-lisp
       (defun smeat-abort (&optional index )
         "Sends USR1 signal to houdini which aborts the smeat client.
       INDEX is used to select which houdini instance to send to if
       multiple instances exist."
         (interactive"p")
         (when (< index 1) (setq index 1))
         (let ((hou-pid (pid-houdini index)))
           (shell-command (concat "kill -s USR1 " hou-pid))))
     #+end_src
**** Preproccess
     #+begin_src emacs-lisp
       (defun preprocess-fix-macros ()
         "Fix expanded macros when running only the preprocess on a file.
       For example: g++ <flags> -E <file>.  Since they are expanded into
       a single line which makes them hard to debug."
         (interactive)
         (let* ((start (if (use-region-p) (region-beginning) (point)))
                (end (if (use-region-p) (region-end) (point-max)))
                (regex-map '(":[ ]" ";" "{" "}[ ]"))
                (regex (mapconcat (lambda (x) (format "\\(%s\\)" x)) regex-map "\\|")))
           (goto-char start)
           (while (search-forward-regexp regex end t)
             (newline)
             (setq end (1+ end)))
           (indent-region start (point))
           (goto-char start)))
     #+end_src
**** Make
***** Functions to speed up the port of old style Makefiles to using modules.
     #+begin_src emacs-lisp
       (defun make-boost-components ()
         "Convert old style boost libs to module style"
         (interactive)
         (let ((begin) (end))
           (if (use-region-p)
               (progn (setq begin (region-beginning) end (region-end)))
             (progn (setq begin (point-min) end nil)))
           (goto-char begin)
           (while (re-search-forward
                   (concat "\\$(\\(?:EXECS\\|LIBS\\))_LIBS \\+= "
                           "\\$(BOOST_LIB_DIR)/libboost_\\(.*?\\)\\.a") end t)
             (replace-match "BOOST_COMPONENTS += \\1"))))

       (defun make-include-to-modules ()
         "Convert old Makefile's INCLUDE to using modules"
         (interactive)
         (let ((begin) (end))
           (if (use-region-p)
               (progn (setq begin (region-beginning) end (region-end)))
             (progn (setq begin (point-min) end nil)))
           (goto-char begin)
           (while (re-search-forward
                   "INCLUDES \\+= \\$(\\(.*\\)_INC_DIR)" end t)
             (replace-match
              (concat "MODULES += " (downcase (match-string-no-properties 1))) t ))))

       (defun make-mkl-module ()
         "Convert old mkl static libs to using the mkl module's flags"
         (interactive)
         (let ((begin) (end))
           (if (use-region-p)
               (progn (setq begin (region-beginning) end (region-end)))
             (progn (setq begin (point-min) end nil)))
           (goto-char begin)
           (when (re-search-forward
                  (concat "\\$(\\(?:EXECS\\|LIBS\\))_LIBS \\+= "
                          "\\$(MKL_STATIC_LAYERED_LIBS)") end t)
             (replace-match "MKL_USE_STATIC_LIBS = YES"))))

       (defun make-eigen-module ()
         "Convert eigen cxxflag to using the eigen module's flags"
         (interactive)
         (let ((begin) (end))
           (if (use-region-p)
               (progn (setq begin (region-beginning) end (region-end)))
             (progn (setq begin (point-min) end nil)))
           (goto-char begin)
           (when (re-search-forward
                  "X?CXXFLAGS \\+= -DEIGEN_USE_MKL_ALL" end t)
             (replace-match "EIGEN_USE_MKL = YES"))))

       (defun make-openvdb-module ()
         "Convert openvdb cxxflag to using the openvdb module's flags"
         (interactive)
         (let ((begin) (end))
           (if (use-region-p)
               (progn (setq begin (region-beginning) end (region-end)))
             (progn (setq begin (point-min) end nil)))
           (goto-char begin)
           (when (re-search-forward
                  "X?CXXFLAGS \\+= -DOPENVDB_3_ABI_COMPATIBLE" end t)
             (replace-match "OPENVDB_USE_ABI_3 = YES"))))

       (defun make-insert-toolchain (&optional toolchain)
         "Insert TOOLCHAIN = TOOLCHAIN, where the last is the variable TOOLCHAIN."
         (interactive "sName of toolchain to use: ")

         (when (not toolchain) (setq toolchain "gcc") )

         (let ((begin) (end))
           (if (use-region-p)
               (progn (setq begin (region-beginning) end (region-end)))
             (progn (setq begin (point-min) end nil)))
           (goto-char begin)
           ;; Move to the end of the _SRCS
           (while (re-search-forward "\\$(\\(?:EXECS\\|LIBS\\))_SRCS \\+= .*" end t))

           (insert (concat "\n\nTOOLCHAIN = " toolchain))))

       (defun make-delete-libpaths-and-rpath ()
         "Delete LIBPATHS += and RPATH_LIBSPATHS from the makefile"
         (interactive)
         (let ((begin) (end))
           (if (use-region-p)
               (progn (setq begin (region-beginning) end (region-end)))
             (progn (setq begin (point-min) end (point-max))))
           (delete-matching-lines "\\(?:RPATH_\\)?LIBPATHS \\+= .*" begin end )))

       (defun make-delete-libs ()
         "Delete $(EXECS/LIBS)_LIBS += lines from the makefile"
         (interactive)
         (let ((begin) (end))
           (if (use-region-p)
               (progn (setq begin (region-beginning) end (region-end)))
             (progn (setq begin (point-min) end (point-max))))
           (delete-matching-lines "\\$(\\(?:EXECS\\|LIBS\\))_LIBS \\+= .*" begin end )))

       (defun convert-make-to-modules ()
         "Convert old makefile to using modules"
         (interactive)
         (make-insert-toolchain)
         (make-include-to-modules)
         (make-mkl-module)
         (make-eigen-module)
         (make-openvdb-module)
         (make-boost-components)
         (make-delete-libpaths-and-rpath)
         (make-delete-libs))
     #+end_src
*** Modes
**** Editing doc strings in the Make project

     Using #: to mark comments as docstrings for the parser. But
     they're a pain to format using fill-paragraph. Deriving a mode
     from makefile-gmake-mode that changes the comments to match these
     tags to easier editing. Note that it will not see # as comments
     anymore and will mess up the format for those, only use this mode
     when editing the docstrings.

     Another option would be to modify the `paragraph-start' regexp
     but it's a pain to get it right and you'll need to change the
     `fill-prefix' to make it work. Which messes up the the
     rest. Probably better when dealing with doxygen comments as this
     [[https://stackoverflow.com/q/1972219][stackoverflow question]] is wondering about.

     #+begin_src emacs-lisp
       (define-derived-mode makefile-bs-mode makefile-gmake-mode "BSmakefile"
         "An adapted `makefile-mode' that uses #: as comments."
         (setq-local comment-start "#:")
         (setq-local comment-end "")
         (setq-local comment-start-skip "#:+[ \t]*"))
     #+end_src

** Behaviour
   Use bash at work.
   #+begin_src emacs-lisp
     (when dotemacs-is-work (setq explicit-shell-file-name "/bin/bash"))
   #+end_src

   Store work related settings.
   #+begin_src emacs-lisp
     (let ((.work (concat user-emacs-directory ".work.el")))
       (when (file-exists-p .work)
         (load .work)))
   #+end_src
* Bug workarounds
  Workarounds for bugs I have encountered through out the years
** Cursor turns black
   Set the cursor color to white.
   #+begin_src emacs-lisp
     (set-cursor-color "#ffffff")
   #+end_src
** Maximize emacs under KDE
   Issue maximizing emacs with KDE at work
   #+begin_src emacs-lisp
     (setq frame-resize-pixelwise t)
   #+end_src
** Juniper VPN linux 4.5+
   Juniper VPN doesn't work in linux 4.5+, workaround is to disable
   the ipv6.
   #+begin_src sh :tangle no
   echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
   #+end_src
** Tramp hangs after password entry
   :PROPERTIES:
   :CUSTOM_ID:  tramp-hang-workaround
   :END:
   See [[https://www.emacswiki.org/emacs/TrampMode#toc7][EmacsWiki]]
   Simple fix if you don't want to use emacs shells is to add this to your .zshrc
   #+begin_src sh :tangle no
     [[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return
   #+end_src

   Problem with this though it that it messes up with the prompt when
   running a emacs shell. For that use:
   #+begin_src sh :tangle no
     # Tramp and emacs shell workaround
     if [[ $TERM == "dumb" ]]
     then
         # Emacs shell/tramp cannot handle line editing, turning it off.
         unsetopt zle

         # The custom prompt will hang tramp.
         # Change to something simpler and stop
         if [[ $INSIDE_EMACS == '' ]]
         then
             PS1='$ '
             return
         fi
     fi
   #+end_src

   Similar issue will happen with a bash shell on the other end. And
   for that you can just remove the =unsetopt zle=.

   The [[https://www.gnu.org/software/emacs/manual/html_node/tramp/Remote-shell-setup.html][manual]] describe that you can customize the
   =tramp-shell-prompt-pattern= to match your remote prompt. Didn't
   not get that to work. Same with the =Interactive shell prompt= from
   what I can tell tramp doesn't set INSIDE_EMACS to contain tramp. So
   this is the only workaround I found that is working. I.e. tramp
   sets the terminal to dumb when testing a connection but it doesn't
   set INSIDE_EMACS. Those two are set when running a shell either
   locally or remote. When using a tramp connection it sets the
   HISTFILE to be a tramp file. That's the only way I found to
   distinguish between a shell that is running locally or from a tramp
   connection.
** Paragraph fill in empty message-mode buffer
   They changed the formating in emacs 26.1 so everything before
   --text follows this line--
   Is treated as a headline and the first line is indented with some spaces.

   #+begin_src text
     I am sorry about your difficulties with git push.  It is true that in this
         situation
     --text follows this line--
     I am sorry about your difficulties with git push.  It is true that in
     this situation
   #+end_src
   [[https://emacs.stackexchange.com/a/41803][source]]

   Workaround is just to add
   #+begin_src test
   --text follows this line--
   #+end_src

* Notes
** Emacs
*** Lisp in search replace
    To execute a lisp function in replace regexp do \,(<function>)
*** Org
**** Skip code block
     You can use =:tangle no= in the =SRC_BLOCK= to ignore the code
     block from being exported aka tangled. Good for example blocks that
     you don't want to end up in you config file.
**** Create block shortcut
     Create source block type "<s" on a new line and press <tab>
*** Flycheck
**** Tweak flycheck
    To set specific compiler and flags for a specific project you can
    use something like this in a .dir-locals.el file:
    #+begin_src emacs-lisp :tangle no
      ;; File .dir-locals.el
      ( ( c++-mode
          . ((flycheck-c/c++-gcc-executable . "/tools/package/gcc/6.4.0/bin/g++" )
             (flycheck-gcc-language-standard . "c++14")
             (flycheck-gcc-include-path
              . ("/dd/dept/software/users/fredriks/swdevl/corelibs/PRIVATE/include") )
             (flycheck-gcc-includes . ("openvdb/math/Vec3.h"))
             (flycheck-gcc-warnings . ("all"))
             (flycheck-gcc-definitions
              . ("_GLIBCXX_USE_CXX11_ABI=0"
                 "EIGEN_MATRIXBASE_PLUGIN=<DD/Utility/EigenMatrixBaseAddon.hpp>"
                 "DD_OPEN_MESH_POLYMESHT_EXTENSION=<DD/Math/Geometry/OpenMesh/OpenMesh_PolyMeshT_Extension.hpp>"
                 "DD_OPEN_MESH_TRIMESHT_EXTENSION=<DD/Math/Geometry/OpenMesh/OpenMesh_TriMeshT_Extension.hpp>"
                 "DD_CORELIBS_USE_OPENMESH"
                 "DD_CORELIBS_BUILD_LIBS"
                 "EIGEN_MATRIXBASE_PLUGIN=<DD/Utility/EigenMatrixBaseAddon.hpp>"
                 "EIGEN_MATRIX_PLUGIN=<DD/Utility/EigenMatrixAddon.hpp>"
                 ))
             (flycheck-gcc-args
              . ("-B/tools/package/binutils/2.29.1/bin"
                 "-isystem/tools/package/openvdb/4.0.1_dd01/include"
                 "-isystem/tools/package/eigen/3.3.4/include/eigen3"
                 "-isystem/tools/package/embree/2.15.1_gcc4.8/include"
                 "-isystem/tools/package/gtest/1.8.0/include"
                 "-isystem/tools/package/openmesh/6.3/include"
                 "-isystem/tools/package/tbb/4.4.6/include"
                 "-isystem/tools/package/boost/1.61.0/include"
                 "-isystem/tools/package/blosc/1.5.0/include"
                 "-isystem/tools/package/ilmbase/2.2.0/include/Ilmbase"
                 "-isystem/tools/package/ilmbase/2.2.0/include"
                 "-isystem/tools/package/ilmbase/2.2.0/include/OpenEXR"
                 "-isystem/tools/package/corelog/3.0.2/include"
                 "-isystem/tools/package/qhull/2012.1/include"
                 "-isystem/tools/include"
                 )))))
    #+end_src
    For clang just replace gcc with clang.

    If you want to play it more safe you can use the flychecks other
    variables (see C-c ! ?). Note that flycheck-include-path just
    prepend -I for all strings in the list. So for third party libs
    it's better to use -isystem.

    Also prefer flycheck-gcc-includes over adding that in
    flycheck-gcc-args as if you do
    #+begin_src emacs-lisp :tangle no
      (flycheck-gcc-args
       . ("-include openvdb/math/Vec3.h")
      )
    #+end_src
    You'll get an error about cannot find file, even though the file
    actually exist. That's because the thing that parses this and
    passes it to a shell escapes the whitespace after -include. So for
    that to work you'll need to do:

    #+begin_src emacs-lisp :tangle no
      (flycheck-gcc-args
       . ("-includeopenvdb/math/Vec3.h")
      )
    #+end_src
    Which is not that readable.

**** Language standard in c++
    Specify language standard in dir locals file: .dir-locals.el
    For example
    ((c++-mode
      (flycheck-clang-language-standard . "c++14")
      (flycheck-gcc-language-standard . "c++14")))
*** Elisp
**** Elisp Regex
     Link to elisp regular expression
     https://www.gnu.org/software/emacs/manual/html_node/elisp/Regular-Expressions.html
**** Change font size on the fly
     Use commands
     C-x C-+ and C-x C--
**** Doc
     Use C-h f to get docs on function
*** Case-sensitive search
    press M-c after search
*** Remove/Keep lines matching regexp
    use 'keep-lines' to keep lines matching regexp.
    use 'flush-lines' to remove lines matching regexp.
*** See what font is used under cursor
    #+begin_src text :tangle no
      M-x describe-char
    #+end_src
    or
    #+begin_src text :tangle no
      C-u C-x =
    #+end_src
    [[https://stackoverflow.com/a/1242760][source]]
*** Don't truncate messages in *scratch*
    #+begin_src emacs-lisp :tangle no
      (setq eval-expression-print-length nil)
    #+end_src
*** Reload dir-locals for buffer
    #+begin_src emacs-lisp
      (hack-dir-local-variables-non-file-buffer)
    #+end_src
** VCS
*** Git
**** Change message in most recent commit
     git commit --amend [-m ""]
*** Subversion
**** Roll back a tag

     Check out the tags directory. Use --depth=empty to avoid
     populating all the tags as this can take a really long time
     depending on how many tags exist.
     #+begin_src sh :tangle no
       svn checkout SVN_URL/REPO/tags  --depth=empty REPO-tag-fix
     #+end_src

     Locate the revision to roll back to.
     #+begin_src sh :tangle no
       svn log SVN_URL/REPO/tags
     #+end_src

     Then cd into the working copy and update all tags involved in the
     roll back. Otherwise svn will just ignore the roll back.
     #+begin_src sh :tangle no
       cd REPO-tag-fix
       svn up --set-depth=infinity TAG0 TAG1...
     #+end_src

     Roll back to the revision you want by simply merging the tags
     directory backwards to that revision.
     #+begin_src sh :tangle no
       svn merge -rHEAD:REVISION .
     #+end_src

     Where REVISION is the revision number you picked previously. HEAD
     is a svn built in keyword and points to the latest revision.
** Code
*** Run functions when loading/unloading shared libraries
    Call function when shared library is loaded, with gcc use:
    #+begin_src c++
      __attribute__((constructor)) void func(){}
    #+end_src

    Call function when shared lbirary is unloaded, with gcc use:
    #+begin_src c++
      __attribute__((destructor)) void func(){}
    #+end_src
*** Check what indentation rule is used for c++
    Run the function ~c-show-syntactic-information~ normaly bound to.
    #+begin_src :tangle no
    C-c C-s
    #+end_src
    Useful when customizing a style.
*** python
**** Reload module from another path

     First modify the sys.path then call reload to update the
     module. If it's a submodule you're trying to update, update the
     main module first.

     This is useful when developing extensions for gdb and you want to
     replace an already installed and loaded extension with a developer
     version.

     #+begin_src python :tangle no
       import sys

       sys.path.insert(0, 'new/path/to/module')
       reload(module)
     #+end_src
**** Generate etags
     #+begin_src shell :tangle no
       find . -name "*.py" -print | etags -
     #+end_src

     To ignore a specific directory, for example =private= which
     contains build and install artifacts.

     #+begin_src shell :tangle no
       find . -type d -name private -prune -or -name "*.py" -print | etags -
     #+end_src

*** Print out debug info
    #+begin_src sh :tangle no
      readelf --debug-dump=<option> <elf>
    #+end_src

    Print out the decoded source path use the
    src_sh[:tangle no]{--debug-dump=decodedline} option.
** Cli
*** Install fonts local to user
    Install fonts to ~/.fonts then update the fontconfig cache by
    running.
    #+begin_src sh
      fc-cache -v ~/.fonts
    #+end_src
    The option '-v' is just for verbose output and can be skipped.

    To see what fonts are installed run
    #+begin_src sh
      fc-list
    #+end_src
*** Terminfo files (ti)
    To compile FILE run
    #+begin_src sh :tangle no
      tic FILE
    #+end_src
*** Shell
    Stop the shell from echoing the command.
    #+begin_src sh :tangle no
      stty -echo
    #+end_src
**** Shell script
***** Argument parsing
      A good way of parsing the arguments for a shell script is using
      getopt (enhanced). There's also built in shell command in bash
      called getopts. But that one doesn't handle long options.

      To use getopt in a script simply do:

      #+begin_src sh
         # Use getopt to parse the command-line arguments
         _args=$(getopt --options h --longoptions workspace:,update::,help -- "$@")
         if [[ $? != 0 ]]
         then
             echo "Try '$0 --help for more information.'" >&2
             exit $_error_input
         fi

         eval set -- "$_args"

         while [[ $# -gt 0 ]]; do
             case "$1" in
                 --workspace)
                     _workspace=$2
                     shift 2
                     ;;
                 --update)
                     _update_func=update
                     # Filters separated by comma
                     for arg in ${2//,/ }
                     do
                         _filter[$arg]=0
                     done
                     shift 2
                     ;;
                 -h|--help)
                     echo -e "${help}"
                     exit
                     ;;
                 --)
                     # End of command-line arguments
                     shift
                     break
                     ;;
             esac
         done
      #+end_src
** Programs
*** find
**** Ignore directories while searching
     For example while searching for file named foobar, ignore all .svn
     directories.
     #+begin_src sh
       find . -not \( -path '*/.svn' -prune \) -name "foobar"
     #+end_src
*** grep
    Print only the grouping of the regex that matched

    Can use perl's look around assertions. For example only print out
    the ticket number of a tool that outputs
    #+begin_src text :tangle no
    Ticket created: 145704
    #+end_src

    #+begin_src shell :tangle no
    tool | grep -Po "Ticket created: \K145704"
    #+end_src
    [[https://unix.stackexchange.com/a/13472][source]]
*** ssh
**** ssh agent
     Use the ssh agent to cache the private key to a terminal
     #+begin_src sh
       eval $(ssh-agent)
       ssh-add ~/.ssh/private-key
     #+end_src
**** multihop with same key
     Use an intermediate machine (=JUMPHOST=) to ssh to the remote
     host (=REALHOST=) without needing to generate a key on the
     =JUMPHOST=.
     #+begin_src sh
     ssh -A -t -l USER1 JUMPHOST ssh -A -t -l USER2 REALHOST
     #+end_src
**** Setup a socks proxy
     Setup a socks tunnel to HOST at port 9090. The option =-N= is to
     disable the prompt to make it easier to keep track of which
     terminal runs the tunnel.
     #+begin_src sh
     ssh -ND9090 HOST
     #+end_src
*** houdini
**** Expression for string parameters
     Create a keyframe (Alt+LMB or "Channels and keyframes" -> "set Keyframe")
     Then edit the expression.
*** KDE
**** no borders
     When disabled use ALT+F3 to bring the menu back.
*** CMake
    Don't remove the rpath when installing.
    #+begin_src sh :tangle no
      CMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE
    #+end_src

    Specify c++ compiler.
    #+begin_src sh :tangle no
      CMAKE_CXX_COMPILER=$(GCC_PACKAGE_ROOT)/bin/g++
    #+end_src
*** Yum
    Find what package a file belongs to:
    #+begin_src sh :tangle no
      yum whatprovides /path/to/file
    #+end_src
*** rpm
    Find what package a file belongs to:
    #+begin_src sh :tangle no
      rpm -qf /path/to/file
    #+end_src
*** GDB
    Bypass the pretty printer and show the raw data.
    #+begin_src :tangle no
    p/r VARIABLE
    #+end_src
*** PDB
    To use pdb with emacs, simply =M-x= =pbd=. If =pdb= does not exist
    as an executable on the machine, use =python -m pdb= instead in
    the prompt.

    To change working directory (default it uses the path of the script). Use
    #+begin_src python :tangle no
    import os; os.chdir('PATH')
    #+end_src
    in the =pdb= prompt.
*** Ledger
**** Check what you spend on X
    #+begin_src sh
      ledger -f data.dat reg payee "X" -s
    #+end_src
**** Scripts
     #+begin_src sh
       env LEDGER_FILE=data.dat scripts/cashflow.sh
     #+end_src
*** Github
**** Preview site of a git hosted website
     Prepend to the original url.
     #+begin_src org :tangle no
       http://htmlpreview.github.io/?
     #+end_src
     For example to see an older page of the embree docs.
     #+begin_src org :tangle no
       https://htmlpreview.github.io/?https://raw.githubusercontent.com/embree/embree.github.com/v2.15.0/index.html
     #+end_src
     source: [[https://stackoverflow.com/questions/8446218/how-to-see-an-html-page-on-github-as-a-normal-rendered-html-page-to-see-preview][stackoverflow]]
*** gcc
**** Generate a list of all defined macros
     cpp -dM /dev/null
***** Check what __cplusplus is set to when setting a language standard in c++
      Need to tell cpp that we only are interested in c++ then we can
      just pass the flags we want.

      For example check what __cplusplus is set to when using c++14.
      #+begin_src sh
        cpp -dM -x c++ -std=c++14 /dev/null | grep __cplusplus
      #+end_src
**** Trace undefined symbol
     use ld's --trace-symbol=<symbol> when linking to get a list of
     what file(s) are using that symbol. Using it with gcc it would be
     #+begin_src sh :tangle no
       gcc <options> -Wl,--trace-symbols=<symbol>
     #+end_src
**** Don't allow undefined symbols in shared libraries
     When enabled it will error out if it finds any undefined symbols
     when linking a shared library.
     #+begin_src sh :tangle no
       gcc <options> -Wl,--no-undefined
     #+end_src
     or
     #+begin_src sh :tangle no
       gcc <options> -Wl,z defs
     #+end_src

**** Record flags in object file
     Will record the flags used to build the object into the object
     file.
     #+begin_src sh :tangle no
       gcc -frecord-gcc-switches
     #+end_src

     There is also =-grecord-gcc-switches= that works similarly.

     To extract the flags from the object file:
     #+begin_src sh :tangle no
       objdump -s -j .GCC.command.line <object file> | sed -En 's/ [[:xdigit:]]{4}( [[:xdigit:] ]{8}){4}  ([^ ]*)/\2/p' | tr -d "\n" | sed -E -e 's/\.-/ -/g' -e 's/[. ]+$/\n/'
     #+end_src
**** Output absolute path to a library

     #+begin_src sh :tangle no
       gcc -print-file-name=<library>
     #+end_src

     This will print out the absolute path to the =<library>=. The
     library needs to have it's prefix =lib= and extenssion for it to
     print it out. For example

     #+begin_src sh :tangle no
       gcc -print-file-name="stdc++"
     #+end_src

     Will just print out =stdc++=. Where as

     #+begin_src sh :tangle no
       gcc -print-file-name="libstdc++.so"
     #+end_src

     Will print out the absolute path to the =libstdc++= it will use
     to link against.
**** Print only the commands it will run

     #+begin_src sh :tangle no
       gcc -###
     #+end_src

     It's similar to =-v= except it will quote the arguments and not
     run the commands
